### ISSUE TITLE
R Studio Crashing When Reading csv

### ISSUE THREAD

**Issue by medewitt** [r-lib/vroom#103]
On Windows 10, R 3.6.0 RStudio crashes when reading in a decent sized data set with `vroom`. I can read with `read_csv` and `fread` so it appears `vroom` related. When I run the code below R Studio crashes.

```
# libraries ---------------------------------------------------------------

library(tidyverse)
library(vroom)

# raw data ----------------------------------------------------------------

my_file <- "https://nces.ed.gov/ipeds/datacenter/data/EF2017A_Data_Stata.zip"

temp <- tempfile()

download.file(url = my_file, temp)

dat <- vroom(unz(temp, "ef2017a_data_stata.csv"))
```

**Comment by jimhester** [comment]
Thanks! I can reproduce the issue, a workaround is to call vroom with `progress = FALSE`. I will figure out what is wrong and fix it soon.
