### ISSUE TITLE
Required package not found

### ISSUE THREAD

**Issue by st-pasha** [r-lib/vroom#104]
I just tried to run `vroom` for the first time, and getting the following error:
```
> require(vroom)
Loading required package: vroom
> vroom('test.csv')
Error in loadNamespace(name) : there is no package called ‘testthat’
```
It is easy to fix, of course, but just wanted to let you guys know that some dependency is not properly specified in the package's metadata.

**Comment by jimhester** [comment]
Thanks, I actually noticed this a few days ago after the release, but had not yet committed and pushed the change.
