### ISSUE TITLE
Use the flights dataset in the getting started vignette?

### ISSUE THREAD

**Issue by jimhester** [r-lib/vroom#108]
I used it in https://www.tidyverse.org/articles/2019/05/vroom-1-0-0/. It is somewhat more exciting than good ol' mtcars.

**Comment by jimhester** [comment]
Also open to possibly other more interesting datasets, ideally ones that contains all the different data types vroom supports.

**Comment by randomgambit** [comment]
@jimhester why dont you use some of the big datasets here https://github.com/awesomedata/awesome-public-datasets#finance ? This would make the advantage of using `vroom` clearer.

**Comment by jimhester** [comment]
Because those datasets would need to be in a data package in order to use them.
