### ISSUE TITLE
vroom::col_date fails to parse single digit month and day

### ISSUE THREAD

**Issue by kiernann** [r-lib/vroom#123]
I'm working with about 100 different files mixed between CSV and TSV but otherwise the same (another great reason to `vroom()`).

When I was using `readr::read_csv()` and `readr::read_tsv()` and binding with `dplyr::bind_rows()`, the date column was able to parse just fine with `readr::col_date("%m/%d/%Y")`.

Using the exact same `col_type = cols()` line in `vroom::vroom()` returns many more `NA` values alongside a handful of correctly parsed dates.

Here is the data I get after combining 8 different `readr::read_delim()` tibbles:
```
> dim(nj)
[1] 879485     34
> sample(nj$cont_date, 6)
[1] "2013-02-11" "1993-12-03" "2007-08-13" "1997-10-07" "1997-02-18" "2000-03-10"
> sum(is.na(nj$cont_date))
[1] 4485
```

Here's what I get after doing the same thing in an _awesome_ single `vroom::vroom()` tibble:
```
> dim(nx)
[1] 879485     34
> sample(nx$cont_date, 5)
[1] NA           NA           NA           "2013-10-16" NA 
> sum(is.na(nx$cont_date))
[1] 701768
```

As far as I can tell, all the other columns are parsing fine. Even if I read in the `cont_date` variable as character and parse it after the fact with `readr::parse_date("%m/%d/%Y")`, I get the same data as with `readr::read_delim(col_type = readr::col_date("%m/%d/%Y"))`

Here are the files I'm working with, for reference:

* https://www.elec.state.nj.us/download/Data/Gubernatorial/All_GUB_Text.zip
* https://www.elec.state.nj.us/download/Data/Legislative/All_LEG_Text.zip
* https://www.elec.state.nj.us/download/Data/Countywide/All_CW_Text.zip
* https://www.elec.state.nj.us/download/Data/PAC/All_PAC_Text.zip

In each ZIP there are a couple dozen TXT files with either tab or comma delimiters.

**Comment by kiernann** [comment]
This issue went away when I ran the same code on my home computer. I'm lost, but the issue must be on my end.

**Comment by jimhester** [comment]
A reprex for this is 

``` r
library(vroom)
vroom("x\n10/04/2014\n", col_type = list(x = col_date("%m/%d/%y")))
#> # A tibble: 1 x 1
#>   x         
#>   <date>    
#> 1 NA
```

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Not entirely sure why this is happening, if I were to guess the format is not being passed properly to the parsing function.

**Comment by edzer** [comment]
@jimhester format seems to be properly passed to `parse_date`, and the following works:
```r
library(vroom)
vroom("x\n10/04/2014\n", col_type = list(x = col_date("%m/%d/%Y"))) # Y, not y
# format:[%m/%d/%Y]
# 10/04/2014 res:1
# # A tibble: 1 x 1
#   x         
#   <date>    
# 1 2014-10-04
```

**Comment by edzer** [comment]
The problem seems to be dates containing single-digit months or days:
```r
Rscript -e 'vroom::vroom("x\n5/4/2014\n", col_type = list(x = vroom::col_date("%m/%d/%Y")))'
# A tibble: 1 x 1
  x         
  <date>    
1 NA        
```
but I get currently stuck in the parser code.
