### ISSUE TITLE
feature request: handling multiple files in a zip

### ISSUE THREAD

**Issue by randomgambit** [r-lib/vroom#125]
Hi @jimhester I am trying to use `vroom` on `zip` archives that contain multiple files.

At the moment, I think `vroom` reads the first file in the zip by default. Indeed, I created a `zip` archive containing two copies of the example files we used yesterday:

```
> test <- vroom('/mypath/myzipped.zip', col_names = c('a','b','c','d'))
Multiple files in zip: reading 'file.out'
Observations: 1,167                                                                                                                
Variables: 4
chr [3]: a, b, c
dbl [1]: d
```
Only the first file `file.out` is being read. I wonder if `vroom` could directly read all the files in the archive in one go. What do you think?

**Comment by jimhester** [comment]
I don't think we could do this automatically, too many zip files have heterogeneous files. You can write a wrapper function to do this without a lot of work however, e.g.

```r
read_all_zip <- function(file, ...) {
  filenames <- unzip(file, list = TRUE)$Name
  vroom(purrr::map(filenames, ~ unz(file, .x)), ...)
}
```

**Comment by randomgambit** [comment]
thanks this is what I ended up doing but I wondered if using `unz` every time was inefficient.

**Comment by randomgambit** [comment]
@jimhester yes, good idea. Something unrelated: I get 150MB/s with vroom using connections. I wonder if I should use `VROOM_CONNECTION_SIZE` to improve the speed. Would that help?

**Comment by jimhester** [comment]
No, not likely.

**Comment by randomgambit** [comment]
makes sense  thanks for the clarification
