### ISSUE TITLE
Vroom::room() reads less records than actual records

### ISSUE THREAD

**Issue by goleng** [r-lib/vroom#130]
Hi, 

The vroom package provides a lot of speed improvement compare with the readr's read_delim function. However, I noticed for all **gzip** files I have, whenever I read in the data using vroom function, the records are way fewer than the actual record in the original file. Using **read_csv** and **read_delim** return the actual record in the files all the time. I've tried this with several gzip data files and the **vroom** results are always fewer. Is there anything that I'm missing? Below is the exact code:

`d <- vroom::vroom(
    file = file_path,
    delim = ",",
    col_names = TRUE,
    trim_ws = TRUE,
    na = c("", "NA")
  )`

**Comment by jimhester** [comment]
Please try with the latest devel version of vroom, this sounds like https://github.com/r-lib/vroom/issues/122, which has been fixed in the current devel version.

```r
devtools::install_github("r-lib/vroom")
```

**Comment by eipi10** [comment]
I had this problem with the CRAN version. When read by `vroom`, about 100,000 rows were missing (out of 2.4 million total) in a set of three csv files. I found this issue, installed the development version of `vroom`, and can confirm that `vroom` now reads in all of the data in my test file.
