### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by GiulioCentorame** [r-lib/vroom#133]
Hello there! I found this problem while compiling the libraries when I install the package from install.packages() (OS is Scientific Linux 6.6 server):

`altrep.cc: In function 'void vroom_materialize(Rcpp::List)':
altrep.cc:23: error: expected primary-expression before '(' token
altrep.cc:23: error: expected primary-expression before '[' token
altrep.cc:23: error: expected primary-expression before ',' token
make: *** [altrep.o] Error 1
ERROR: compilation failed for package 'vroom'
`

**Comment by jimhester** [comment]
Are you sure your compiler supports C++11? vroom requires a C++11 compatible compiler.

**Comment by GiulioCentorame** [comment]
That worked, I retried with a more recent version and it went flawlessly. Thank you!
