### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by MikeJohnPage** [r-lib/vroom#134]
On the vroom site, the documentation under the subheading 'Column type'  on the ['Get Started'](http://vroom.r-lib.org/articles/vroom.html) article appears to be wrong for some of the column types:

- `col_number()` [n], numbers containing the `grouping_mark`
- `col_date(format = "")` [D]: with the locale’s `date_format`.
- `col_time(format = "")` [t]: with the locale’s `time_format`.
- `col_datetime(format = "")` [T]: ISO8601 date times.

This contrasts the documentation for `col_types` for `vroom()` on the [references](http://vroom.r-lib.org/reference/vroom.html) tab:

> Alternatively, you can use a compact string representation where each character represents one column: c = character, i = integer, n = number, d = double, l = logical, f = factor, D = date, T = date time, t = time, ? = guess, or _/- to skip the column.

I was trying to read a date time using `[T]:` and it wasn't until I scanned the reference docs that I found I should be using `T` instead.

I presume this is a mistake in the docs? If not the use of `[T]:` etc. would benefit from more explanation (in my opinion!).

**Comment by jimhester** [comment]
Sorry! Should now be fixed https://github.com/r-lib/vroom/commit/9ba6eb32291d6319118f40e0525ca4be938959f0
