### ISSUE TITLE
Null integers read in as zero

### ISSUE THREAD

**Issue by alastairmatheson** [r-lib/vroom#135]
When I read in a series of csv files, null cells are being read in as zero if I specify the col type as integer. Specifying it as double leads to a correct NA. If I don't specify a col type, vroom reads it in as a double and also correctly uses NA.

I checked readr::read_csv and the same file yields NA for both integer and double col types. Similarly, data.table::fread produces an integer type and NA value.

**Comment by jimhester** [comment]
Thanks for opening the issue, it should now be fixed!
