### ISSUE TITLE
vroom sends 'R character strings are limited to 2^31-1 bytes' error for a big .CSV file

### ISSUE THREAD

**Issue by kallom** [r-lib/vroom#136]
After trying to open a 6.6 million lines .CSV file, vroom sends this error: 
                                                                                                                                                  
Error in structure(.Call(C_objectSize, x), class = "object_size") : 
  R character strings are limited to 2^31-1 bytes

**Comment by jimhester** [comment]
I don't suppose the file is publicly available?

**Comment by jimhester** [comment]
Also are you running this in RStudio or on the command line? There isn't anything in vroom that would be calling object_size, but RStudio does

**Comment by kallom** [comment]
No, contents are confidential, but it is a simple .CSV, slightly less than 1 GB, 6634693 rows.
Both fread and read_csv  process it without any problems, even read.csv reads it (but you have to be patient).
 Column types are:
cols(
  X1 = col_datetime(format = ""),
  X2 = col_character(),
  X3 = col_character(),
  X4 = col_character(),
  X5 = col_character(),
  X6 = col_integer(),
  X7 = col_integer(),
  X8 = col_character(),
  X9 = col_double(),
  X10 = col_double(),
  X11 = col_double(),
  X12 = col_double(),
  X13 = col_double(),
  X14 = col_double(),
  X15 = col_double(),
  X16 = col_double(),
  X17 = col_skip(),
  X18 = col_character()
)

**Comment by kallom** [comment]
You are right, running it from RGui (64 bit) fixes the problem, so it has to do something with what RStudio does after vroom finished. On the other hand, I am routinely dealing with bigger files from within RStudio using readr and fread and haven't seen this message so far.

**Comment by jimhester** [comment]
It is a bug in RStudio with Altrep objects, you need to update to 1.2.1335+ as mentioned in the vroom readme https://github.com/r-lib/vroom#rstudio-caveats

**Comment by kallom** [comment]
I see, fair enough, thanks.
