### ISSUE TITLE
vroom skips rows

### ISSUE THREAD

**Issue by kanishkamisra** [r-lib/vroom#139]
Hi! I am trying to read files found in http://nlp.stanford.edu/data/glove.6B.zip (the smallest sized file in it is named `glove.60B.50d.txt`)

All files have 400000 rows and the number of columns are the prefixes to "d" in the filename plus one (as the rowname), for example the smallest file I mentioned above has 51 dimensions where the first column is of type character and the rest are all floats. 

vroom reads the number of columns accurately but produces less than the desired number of rows. 

Here is a reprex (well not really since the txt file is zipped in the online resource):

```r
library(vroom)

glove <- vroom("~/glove.6B/glove.6B.50d.txt", col_names = FALSE)
#> Observations: 349,864
#> Variables: 51
#> chr [ 1]: X1
#> dbl [50]: X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16, X17, X18...
#> 
#> Call `spec()` for a copy-pastable column specification
#> Specify the column types with `col_types` to quiet this message

glove
#> # A tibble: 349,864 x 51
#>    X1         X2      X3     X4      X5      X6      X7     X8      X9
#>    <chr>   <dbl>   <dbl>  <dbl>   <dbl>   <dbl>   <dbl>  <dbl>   <dbl>
#>  1 the    0.418   0.250  -0.412  0.122   0.345  -0.0445 -0.497 -0.179 
#>  2 ,      0.0134  0.237  -0.169  0.410   0.638   0.477  -0.429 -0.556 
#>  3 .      0.152   0.302  -0.168  0.177   0.317   0.340  -0.435 -0.311 
#>  4 of     0.709   0.571  -0.472  0.180   0.544   0.726   0.182 -0.524 
#>  5 to     0.680  -0.0393  0.302 -0.178   0.430   0.0322 -0.414  0.132 
#>  6 and    0.268   0.143  -0.279  0.0163  0.114   0.699  -0.513 -0.474 
#>  7 in     0.330   0.250  -0.609  0.109   0.0364  0.151  -0.551 -0.0742
#>  8 a      0.217   0.465  -0.468  0.101   1.01    0.748  -0.531 -0.263 
#>  9 rein…  0.601  -0.727   0.711 -1.58    0.317  -0.676   0.408  0.662 
#> 10 koon… -0.264   0.353  -1.89  -0.675  -0.0616 -0.132   0.253  0.0731
#> # … with 349,854 more rows, and 42 more variables: X10 <dbl>, X11 <dbl>,
#> #   X12 <dbl>, X13 <dbl>, X14 <dbl>, X15 <dbl>, X16 <dbl>, X17 <dbl>,
#> #   X18 <dbl>, X19 <dbl>, X20 <dbl>, X21 <dbl>, X22 <dbl>, X23 <dbl>,
#> #   X24 <dbl>, X25 <dbl>, X26 <dbl>, X27 <dbl>, X28 <dbl>, X29 <dbl>,
#> #   X30 <dbl>, X31 <dbl>, X32 <dbl>, X33 <dbl>, X34 <dbl>, X35 <dbl>,
#> #   X36 <dbl>, X37 <dbl>, X38 <dbl>, X39 <dbl>, X40 <dbl>, X41 <dbl>,
#> #   X42 <dbl>, X43 <dbl>, X44 <dbl>, X45 <dbl>, X46 <dbl>, X47 <dbl>,
#> #   X48 <dbl>, X49 <dbl>, X50 <dbl>, X51 <dbl>
```
It seems to have read only 349,864 rows instead of 400,000. 

I can try and host one of the files on google drive and make it accessible to you if that helps in reproducing it, that way you dont have to download the entire zipped directory. 

Please let me know if I can provide anything else that can help in solving this problem

Thanks!

**Comment by jimhester** [comment]
Please try with the development version of vroom, I think this is already fixed.

**Comment by kanishkamisra** [comment]
I tried doing that and got the same issue :(

**Comment by kanishkamisra** [comment]
I have hosted the smallest file [here](https://drive.google.com/file/d/1ziROqFJr9CLPtcdu_rWfn7waYrmgQiak/view?usp=sharing) in case you want to replicate my example.

**Comment by jimhester** [comment]
There is a unpaired double quote in the file, disabling quoting with `quote = ""` fixes the issue.

**Comment by kanishkamisra** [comment]
Oh :man_facepalming: thanks for the quick response!
