### ISSUE TITLE
problem with scientific notation in text file

### ISSUE THREAD

**Issue by vjcitn** [r-lib/vroom#164]
```
tst = "CHR POS SNP Tested_Allele Other_Allele Freq_Tested_Allele BETA SE P N INFO
16 28825405 rs7500654:G:A A G 0.0046 -0.0057 0.014 0.6866 594148 0.979777
16 28825605 rs2008514:G:A A G 0.3834 0.0281 0.0017 5.414e-64 798952 0.999808
16 28836205 rs4451951:T:C T C 0.5377 -0.0278 0.0018 5.038e-52 569736 0.999848"
con = textConnection(tst)
datf = read.delim(con, sep=" ")
tf = tempfile()
write.table(datf, tf, row.names=FALSE, sep=" ")
summary(data.table::fread(tf)$P)
summary(vroom::vroom(tf, delim=" ")$P)
```
for fread:
```
> summary(data.table::fread(tf)$P)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.2289  0.3433  0.6866 
```
for vroom:
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 0.000e+00 1.000e+00 1.835e+71 2.753e+71 5.506e+71 
```

**Comment by sinarueeger** [comment]
Came across the same problem (also with GWAS summary stats). Here is an example with a (much) larger dataset. 

``` r

path_to_file <- "https://portals.broadinstitute.org/collaboration/giant/images/6/6e/Whradjbmi.giant-ukbb.meta-analysis.combined.23May2018.HapMap2_only.txt.gz" 

data_fread <- data.table::fread(path_to_file)
data_vroom <- vroom::vroom(path_to_file)
#> Observations: 2,516,890
#> Variables: 11
#> chr [3]: SNP, Tested_Allele, Other_Allele
#> dbl [8]: CHR, POS, Freq_Tested_Allele, BETA, SE, P, N, INFO
#> 
#> Call `spec()` for a copy-pastable column specification
#> Specify the column types with `col_types` to quiet this message

summary(data_fread$P)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  0.0000  0.1125  0.3666  0.4054  0.6720  1.0000
summary(data_vroom$P)
#>      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#> 0.000e+00 0.000e+00 0.000e+00 1.774e+69 1.000e+00 9.210e+74
```

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup> 

Interestingly, it works for some of the scientific notation, but not all of them. 

``` r
which(data_vroom$P > 1)
which(data_vroom$P < 1e-50)
```

**Comment by TobCap** [comment]
I also had encountered this bug. It might be a minimum reproducible code.

```r
> suppressMessages(vroom::vroom("h1,h2\n1e-63,1e-64"))
# A tibble: 1 x 2
        h1          h2
     <dbl>       <dbl>
1 1.00e-63 0.000000001
```

This comes from `vroom_dbl.cc:179` which calls out of range static array access `powersOf10[i]` with index i >= 6. (The out of range values may change depending on your running machine)

```
(gdb) p powersOf10[5]
$18 = 1.0000000000000001e+32
(gdb) p powersOf10[6]
$19 = 1000000000
(gdb) p powersOf10[7]
$20 = 4.6676289543700564e+252
(gdb) p powersOf10[8]
$21 = 8.6391144097190899e-13
(gdb) p powersOf10[9]
$22 = 5.2855936391327863e+180
```

The same thing happens when you read `1e64` due to the same reason.
I'm not sure that removing comment-out of `vroom_dbl.cc:72` would solve all this related problems but may help the first step of the investigation.

---

I have a related question:
- Why does vroom prefer vroom_dbl.cc to vroom_num.cc when parsing numbers? Is it performance reason?

**Comment by jimhester** [comment]
> Why does vroom prefer vroom_dbl.cc to vroom_num.cc when parsing numbers? Is it performance reason?

The same reason as readr does, the numeric parser is a much looser parser than the double parser, it is not guessed by default, as it is more likely to result in non-numbers being parsed as numbers.

**Comment by TobCap** [comment]
Thank you for your explanation. Understood

**Comment by jimhester** [comment]
Thank you all for the reproducible examples, I have confirmed that all of them are now producing results from vroom that are equivalent to `data.table` and `read.delim` for these examples.
