### ISSUE TITLE
Emphasize comparison bw just readr and vroom in README

### ISSUE THREAD

**Issue by batpigandme** [r-lib/vroom#165]
Per @MattDowle's tweet, [here](https://twitter.com/mattdowle/status/1150847947740811264?s=21).

Some options/thoughts:

* Make the subheader here more explicit that its' Features: vroom vs readr (or have a subheader under it)
https://github.com/r-lib/vroom/blob/3283f76f56903f1b91003a464bd178741f015b0f/README.Rmd#L67

* Make the asterisk note more explicit (e.g. these are features in vroom and not in readr)
https://github.com/r-lib/vroom/blob/3283f76f56903f1b91003a464bd178741f015b0f/README.Rmd#L91

* Expand feature comparison to include `fread()` (downside there: bc of the use of ALTREP, etc., it's hard to make this apples to apples).

**Comment by mattdowle** [comment]
I'd be disappointed if it's made just a comparison between vroom and readr.  Because fread did a lot of these things first but isn't really getting the credit for that here. I am sensitive to that (to use the word that Hadley uses in similar circumstances).

**Comment by batpigandme** [comment]
Makes sense. And, now that I think about it, feature comparison and benchmarks don't have to be in the same chunk (since benchmarks w/ vroom and DT vary by data types, etc)
