### ISSUE TITLE
Are you sure that vroom can guess the separator automatically like data.table?

### ISSUE THREAD

**Issue by henry090** [r-lib/vroom#167]
Hi, it is not the first time that vroom cannot guess the separator. 
As an example, you can try the following datasets 
https://www.kaggle.com/c/ieee-fraud-detection/leaderboard

**Comment by phileas-condemine** [comment]
same here, i'm using a ";" separated file, I use col_select but I get the error "Evaluation error : objet 'finess' introuvable" meaning the variable can't be found.
When I set explicitly delim=";" it works.

**Comment by jimhester** [comment]
The heuristics used are not perfect and are not as robust as those used in data.table, if it is not working for your dataset set the delimiter explicitly, which is also safer if you know what the delimiter is.

There are existing issues related to this #141 so I am going to close this issues.
