### ISSUE TITLE
Error contains unneeded call

### ISSUE THREAD

**Issue by hadley** [r-lib/vroom#169]
```R
 population <- vroom::vroom("population.csv")
Error in vroom_(file, delim = delim, col_names = col_names, col_types = col_types,  : 
  Evaluation error: 'population.csv' does not exist in current working directory ('/Users/hadley/Documents/shiny/shiny-book')..
```

(also looks like there are two `.` at the end)

**Comment by jimhester** [comment]
This is now better, it was more difficult than it might first appear, because the error was coming from R code called by Rcpp, and Rcpp reformats evaluation errors and adds the call stack unconditionally. So I had to catch the error and then undo the Rcpp formatting.
