### ISSUE TITLE
vroom() error when file contains only header and no line break

### ISSUE THREAD

**Issue by Plebejer** [r-lib/vroom#173]
Here is a minimal example: 

    > library(readr)
    > library(vroom)
    > write_file("a,b,c", "empty.csv")

    > read_csv("empty.csv")
    Parsed with column specification:
      cols(
        a = col_character(),
        b = col_character(),
        c = col_character()
      )
    # A tibble: 0 x 3
    # … with 3 variables: a <chr>, b <chr>, c <chr>

    > vroom("empty.csv")
    New names:                                                                                                                            
      * `` -> ...2
    * `` -> ...3
    * `` -> ...4
    * `` -> ...5
    * `` -> ...6
    * … and 131061 more problems
    Observations: 0
    Variables: 131,067
    chr [131067]: a,b,c, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,...
    
    Call `spec()` for a copy-pastable column specification
    Specify the column types with `col_types` to quiet this message
    # A tibble: 0 x 131,067
    # … with 131,067 variables: `a,b,c` <chr>, ...2 <chr>, ...3 <chr>, ...4 <chr>, ...5 <chr>, ...6 <chr>, ...7 <chr>, ...8 <chr>,
    #   ...9 <chr>, ...10 <chr>, ...11 <chr>, ...12 <chr>, ...13 <chr>, ...14 <chr>, ...15 <chr>, ...16 <chr>, ...17 <chr>, ...18 <chr>,
    #   ...19 <chr>, ...20 <chr>, ...21 <chr>, ...22 <chr>, ...23 <chr>, ...24 <chr>, ...25 <chr>, ...26 <chr>, ...27 <chr>, ...28 <chr>,
    #   ...29 <chr>, ...30 <chr>, ...31 <chr>, ...32 <chr>, ...33 <chr>, ...34 <chr>, ...35 <chr>, ...36 <chr>, ...37 <chr>, ...38 <chr>,
    #   ...39 <chr>, ...40 <chr>, ...41 <chr>, ...42 <chr>, ...43 <chr>, ...44 <chr>, ...45 <chr>, ...46 <chr>, ...47 <chr>, ...48 <chr>,
    #   ...49 <chr>, ...50 <chr>, ...51 <chr>, ...52 <chr>, ...53 <chr>, ...54 <chr>, ...55 <chr>, ...56 <chr>, ...57 <chr>, ...58 <chr>,
    #   ...59 <chr>, ...60 <chr>, ...61 <chr>, ...62 <chr>, ...63 <chr>, ...64 <chr>, ...65 <chr>, ...66 <chr>, ...67 <chr>, ...68 <chr>,
    #   ...69 <chr>, ...70 <chr>, ...71 <chr>, ...72 <chr>, ...73 <chr>, ...74 <chr>, ...75 <chr>, ...76 <chr>, ...77 <chr>, ...78 <chr>,
    #   ...79 <chr>, ...80 <chr>, ...81 <chr>, ...82 <chr>, ...83 <chr>, ...84 <chr>, ...85 <chr>, ...86 <chr>, ...87 <chr>, ...88 <chr>,
    #   ...89 <chr>, ...90 <chr>, ...91 <chr>, ...92 <chr>, ...93 <chr>, ...94 <chr>, ...95 <chr>, ...96 <chr>, ...97 <chr>, ...98 <chr>,
    #   ...99 <chr>, ...100 <chr>, …
    
    > sessionInfo()
    R version 3.6.1 (2019-07-05)
    Platform: x86_64-conda_cos6-linux-gnu (64-bit)
    Running under: elementary OS 5.0 Juno
    
    Matrix products: default
    BLAS/LAPACK: /home/gomolka/miniconda3/envs/valinv/lib/libopenblasp-r0.3.6.so
    
    locale:
      [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
    [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
      [1] vroom_1.0.2 readr_1.3.1
    
    loaded via a namespace (and not attached):
      [1] Rcpp_1.0.1       fansi_0.4.0      withr_2.1.2      assertthat_0.2.1 utf8_1.1.4       crayon_1.3.4     R6_2.4.0         magrittr_1.5     pillar_1.3.1     cli_1.1.0        rlang_0.3.4      tools_3.6.1      glue_1.3.1      
    [14] purrr_0.3.2      hms_0.4.2        parallel_3.6.1   compiler_3.6.1   pkgconfig_2.0.2  tidyselect_0.2.5 tibble_2.1.1

**Comment by jimhester** [comment]
Thank you for the reproducible example, this should now be fixed.
