### ISSUE TITLE
documentation implies multiple delimeters supported, but only one recognized

### ISSUE THREAD

**Issue by ecoquant** [r-lib/vroom#174]
_vroom_ documentation for the `vroom` function implies multiple delimeters are supported, as

delim=",\t"

where it says 

> One of [sic] more characters used to delimiter ﬁelds within a record. If NULL the de-
> limiter is guessed from the set of c(",", "\t", " ", "|", ":", ";", "\n").

Unfortunately only one is recognized.  I was attracted to _vroom_ because I thought it might be superior to _data.table_'s `fread` in this respect.  Note that in `fread` if multiple delimiters are supplied it calls it an error. 

I have a file which (stupidly) has both tabs and commas as field delimiters. It would be great to be able to just recognize either, without having to read each line in and then translate.

**Comment by jimhester** [comment]
Sorry for the confusion, however I don't think the documentation implies that, it says _the_ delimiter is guessed, not that multiple delimiters are guessed. Guessing multiple delimiters would cause many false positives for the vast majority of files, which do not use multiple delimiters at once.

I would suggest you preprocess your file converting tabs to commas or vise-versa, then use whatever method you prefer to read them into R.
