### ISSUE TITLE
vroom not available in R 3.5.3

### ISSUE THREAD

**Issue by sanromd** [r-lib/vroom#179]
`install.package("vroom") ` fails with `package ‘vroom’ is not available (for R version 3.5.3)`
as per the documentation in CRAN it should be compatible with R>=3.1, yes?

**Comment by jimhester** [comment]
I am not sure what the issue you are having is, perhaps you are requesting a binary but there is not one available for that R version and OS. But vroom is tested on CI systems back to R 3.2.
