### ISSUE TITLE
Too many open files - Windows

### ISSUE THREAD

**Issue by martindut** [r-lib/vroom#180]
I have a function that creates a list of all the files in various folders on my local drive. I then purrr::map over each file and read the file with vroom::vroom.

```r
getFileslocalfolder = function(folder, type = "", subtype = "", version = ""){
files <- fs::dir_ls(folder, recurse = TRUE, type = "file")
files <- files %>% tibble::enframe(name = NULL, value = "filename")
files <- files %>%
dplyr::mutate(
contents = purrr::map(.x = filename, .f = self$getFilelocal, type = type, subtype = subtype, version = version) )

return(files)
}
getFilelocal = function(sfile, type = "", subtype = "", version = ""){
filespec <- self$getFilespec(type, subtype, version)
#vroom::vroom(altrep_opts = FALSE)
#ret <- readr::read_delim(file = sfile, delim = filespec$format_delim, col_names = filespec$col_names, col_types = filespec$col_types, skip = filespec$skip_head)

ret <- vroom::vroom(file = sfile, delim = filespec$format_delim, col_names = filespec$col_names, col_types = filespec$col_types, skip = filespec$skip_head)
return(ret)
}
```

After a while, and having read a few files, the following error appears for each remaining file
**Error in file(con, "r") : cannot open the connection                                                                    
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:/Program Files/RStudio/resources/CITATION': Too many open files**

I tried to set the altrep_opts = FALSE, but then the function cannot read even one file because of some error in the vroom package **Error in standardise_path(file) : 
  argument "file" is missing, with no default **

If I change the vroom::vroom to readr::read_delim, it reads all the files, but takes very long.
I realise that this is a Windows issue, but I really want to get it working with vroom on Windows.

Thanks for a great package so far!

**Comment by jimhester** [comment]
I can confirm the issue, here is a reproducible example. It seems like the file handles are not being closed and released to the OS properly.

```r
library(vroom)

dir <- tempfile()
dir.create(dir)
on.exit(unlink(dir, recursive = TRUE))

for (i in seq_len(2000)) {
  vroom_write(
    tibble::tibble(
      x = rnorm(10),
      y = rnorm(10),
    ),
    file.path(dir, paste0(i, ".csv")),
    delim = ",")
}

files <- list.files(dir, pattern = ".*[.]csv", full.names = TRUE)
res <- lapply(files, function(file) vroom::vroom(file, altrep_opts = FALSE, col_types = list()))
```

**Comment by jannikbuhr** [comment]
I can confirm this issue on linux (fedora 30).
