### ISSUE TITLE
LZ4 compression

### ISSUE THREAD

**Issue by chsafouane** [r-lib/vroom#181]
Is it possible to add LZ4 compression when writing files as it is usually much faster than other methods of compression and the size of the output is relatively small (not smaller than all compression methods in vroom)? fst package makes use of it and allows it to write in a very fast way to disk. Thanks !

**Comment by jimhester** [comment]
You can already write to lz4 like you can to any other [compressed format without a built-in R connection](https://vroom.r-lib.org/articles/vroom.html#writing-compressed-files), by using a pipe connection and the appropriate command line tool (`lz4c` in this case) e.g.

```r
vroom_write(mtcars, pipe("lz4c > mtcars.tsv.gz"))
```

**Comment by chsafouane** [comment]
I thought it works just with the ones cited in the article (gzip, lbzip2, etc) but that's really Amazing. Thanks Jim
