### ISSUE TITLE
Mention why vroom_write() prefers tsvs

### ISSUE THREAD

**Issue by hadley** [r-lib/vroom#182]
e.g. in https://vroom.r-lib.org/articles/vroom.html#writing-delimited-files

* Avoids the `;` vs `,` issue
* Less likely to need quoting of fields

**Comment by jimhester** [comment]
Also lets you easily use command line tools such as `cut`, which defaults to using tab as the delimiter.

**Comment by pavopax** [comment]
relatedly, can we add small option:

if path containts "csv", automatically use `delim=","`?

Being used to write_csv, I always forget to specify delim option to write CSVs. 

I would also consider more widely if TSV is better than CSV. Useful reference: https://stackoverflow.com/q/11130120/3217870
