### ISSUE TITLE
vroom isn't that fast on one real world dataset

### ISSUE THREAD

**Issue by xiaodaigh** [r-lib/vroom#185]
See https://www.kaggle.com/xiaodaizj/mortgageriskfeaturetools

data.table reads it in under 10s, and readr tkaes 120s+ but vroom takes about 70s and CSV.jl takes about 30s.

**Comment by jimhester** [comment]
The dataset mentioned is mostly wide numeric data, these results are not terribly surprising.

The performance characteristics of vroom compared to other packages on different types and shapes of files are characterized in the vignettes.
