### ISSUE TITLE
vroom parse missing values incorrectly

### ISSUE THREAD

**Issue by osiris08** [r-lib/vroom#187]
under the following scenario, vroom parse the csv file incorrectly

test data `missing.csv` 

```
col1,col2
1,
2,2
3,
```

parsing it with readr correctly add NA to the data frame
```{r}
readr::read_csv('missing.csv')
```

but vroom treats it a one column
```{r}
vroom::vroom('missing.csv')
```

**Comment by jimhester** [comment]
You need to specify the delim in this case, there isn't enough information to guess it correctly.

``` r
vroom::vroom(
"col1,col2
1,
2,2
3,", delim = ",")
#> Observations: 3
#> Variables: 2
#> dbl [2]: col1, col2
#> 
#> Call `spec()` for a copy-pastable column specification
#> Specify the column types with `col_types` to quiet this message
#> # A tibble: 3 x 2
#>    col1  col2
#>   <dbl> <dbl>
#> 1     1    NA
#> 2     2     2
#> 3     3    NA
```

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
