### ISSUE TITLE
Option to output data.frame/data.table

### ISSUE THREAD

**Issue by 2005m** [r-lib/vroom#189]
What do you think of adding an option to `vroom` to return a `data.frame` or `data.table`?

**Comment by jimhester** [comment]
Converting to `data.frame()` can be done cheaply with `as.data.frame()`, or changing the class of the object.

`data.table` currently forces all altrep vectors to become normal vectors, which defeats the purpose of vroom, so until that changes there isn't much point in outputting a `data.table` either.
