### ISSUE TITLE
Are there known issues with very large data files?

### ISSUE THREAD

**Issue by Shians** [r-lib/vroom#193]
I am having issues reading in 75GB of TSV, the server I'm running RStudio on has 500GB of RAM so it should all fit. However vroom ran for 18 hours without completing and I had to abort it. Are there known issues with reading very large TSVs that I should be aware of before trying to debug further?

**Comment by jimhester** [comment]
No, but there are known issues with older versions of RStudio, as detailed in the README (https://github.com/r-lib/vroom#rstudio-caveats)

**Comment by Shians** [comment]
The original code was running `lapply()` over 3x25GB TSV, the code was run in a RStudio job on RStudio Pro 1.2.5019 so I don't think the resource monitor touches it. I trimmed down the code to run on a simple `vroom` call and ran into the issue fixed in #183. So I imagine some weird interaction potentially occurred in the RStudio job system, `lapply()`, `vroom()` hitting index limits and possibly my server's filesystem which caused the whole thing to just hang. Don't think it's a major concern or likely to occur to anyone else. Thanks Jim!
