### ISSUE TITLE
Filter and Summarize performance on large datasets

### ISSUE THREAD

**Issue by stephen-hayne** [r-lib/vroom#195]
Hi - after reading the benchmark blog and vignette, and running my tests on the Taxi dataset and my own large data, I love the performance on the read of files.  vroom uses all available cores... lovely!   But when filtering (or summarizing), it throttles to just a single core.  

I'm wondering if you have any advice as to how to speed this up.  I've tried multi_dplyr, dopar and rmpi, with varying degrees of success.  Here is my "reproducible code" assuming you have the fare data downloaded and unzip'd:

```r
library(tidyverse)
library(vroom)
Sys.setenv("VROOM_SHOW_PROGRESS"="false")
library(tictoc)

filenames <- fs::dir_ls(path="~/trip/",all=TRUE,glob = "*trip_fare*")
tic()
taxiDF <- vroom::vroom(file = filenames, delim=",", escape_double = FALSE) 
toc()
**39.318 sec elapsed**
tic()
taxiDF <- vroom::vroom(file = filenames, delim=",", escape_double = FALSE) %>%
  filter(payment_type != "UNK")
toc()
**206.095 sec elapsed**
```

**Comment by jimhester** [comment]
There isn't anything to be done, reading strings in R has to be done single threaded as it needs to query and write to R's global string pool and (in this example) the `payment_type` column needs to be fully read before the filtering can happen.
