### ISSUE TITLE
vroom not reading entirely a (possibly) bogus csv?

### ISSUE THREAD

**Issue by randomgambit** [r-lib/vroom#196]
Hello there,

I noticed that `vroom` keeps reading only a small portion of a csv that is being read correctly by `data.table` and `read_csv`. 

I cannot share the file but I'd be happy to create a reprex. How does `vroom` know (or decide) it's the end of the file? Perhaps there is something in my `csv` that tricks `vroom` and not the others? The file is delimited by `|` and has about 200k rows and 300 columns.

Thanks!

**Comment by jimhester** [comment]
Are there embedded newlines in your file by chance? If so you need to use `num_threads = 1`.

**Comment by randomgambit** [comment]
Hi Jim! thanks for jumping in. I dont think so. I tried with `num_threads = 1` but the limited parsing is still there. This is a tricky error because it is totally silent (unless you know exactly how many lines you should get). Any other ideas I can try? Thanks!

**Comment by randomgambit** [comment]
Found the error (I think)!!  A few lines contain some single `"` (likely instead of the pipe `|`). I think this caused `vroom` to either skip the lines or create a massive string that contains many rows. 

I havent found a fix yet but I wonder if `vroom` can detect that something is wrong automatically (I guess like `data.table` or `read_csv`)?

**Comment by jimhester** [comment]
Sorry, I can't help you further without a example that reproduces the issue.

**Comment by randomgambit** [comment]
@jimhester here is a reprex!!

create this little `csv` first.

```
vroom|vroom|vroom|
a | b| c|d
bogus "|hi|hello|
```

then you can see below that `vroom` trims the file.

```
> vroom('/home/bogus.csv',col_names = c('1','2','3','4'), delim = '|')
Observations: 2                                                                                                                      0s
Variables: 4
chr [4]: 1, 2, 3, 4

Call `spec()` for a copy-pastable column specification
Specify the column types with `col_types` to quiet this message
# A tibble: 2 x 4
  `1`   `2`   `3`   `4`  
  <chr> <chr> <chr> <chr>
1 vroom vroom vroom NA   
2 a     b     c     d    
> 
> read_delim('/home/bogus.csv',col_names = c('1','2','3','4'),delim = '|')
Parsed with column specification:
cols(
  `1` = col_character(),
  `2` = col_character(),
  `3` = col_character(),
  `4` = col_character()
)
# A tibble: 3 x 4
  `1`        `2`   `3`   `4`  
  <chr>      <chr> <chr> <chr>
1 vroom      vroom vroom NA   
2 "a "       " b"  " c"  d    
3 "bogus \"" hi    hello NA 
```

**Comment by jimhester** [comment]
The easiest way for you to handle this is passing `quote = ""`.

**Comment by randomgambit** [comment]
got it, thanks.

**Comment by randomgambit** [comment]
actually doing so immediately crashes my R session. does it work for you?

**Comment by randomgambit** [comment]
@jimhester yes I can confirm the immediate crash on `3.6.2`. Can you confirm?
Thanks!

**Comment by jimhester** [comment]
No.

**Comment by randomgambit** [comment]
yes I will try. thanks and happy holidays btw! the crash seems only to occur on windows... on linux your quoting fix worked just fine...

**Comment by randomgambit** [comment]
Hi Jim, it seems the fix does not work in all cases...
