### ISSUE TITLE
Able to read in col_type as `integer64`

### ISSUE THREAD

**Issue by DyfanJones** [r-lib/vroom#198]
Hi All, 
Are the any plans to add column type`integer64` into the column types?

The reason for asking is that I am developing a connectivity package to AWS Athena: https://github.com/DyfanJones/RAthena . Being able to read Athena `bigint` type as `integer64` would be really useful.

Many thanks

**Comment by jimhester** [comment]
No current plans. Is there a reason you decided are not using the [ODBC](https://docs.aws.amazon.com/athena/latest/ug/connect-with-odbc.html) drivers for Athena?

**Comment by DyfanJones** [comment]
Hi @jimhester thanks for the reply so quickly especially on new years eve. `RAthena` has only been created to provide R users another method to connect to AWS Athena utilising the AWS SDK Boto3. This is fairly useful when considering cloud products like AWS Sagemaker. Meaning that only `RAthena` is required to be installed to give an instant connection to AWS Athena, as AWS Sagemaker provides `Boto3` and `reticulate` apart of the default image.

**Comment by jimhester** [comment]
Turns out this was pretty straightforward to do and is an easy win, so it is done and will be in the next release.
