### ISSUE TITLE
Broken benchmark links

### ISSUE THREAD

**Issue by blairj09** [r-lib/vroom#199]
All links to benchmark code on the site (https://vroom.r-lib.org/articles/benchmarks.html) are broken and lead to 404s.

**Comment by jimhester** [comment]
Yes, the benchmarks were moved. They are fixed on the dev pkgdown site https://vroom.r-lib.org/dev/articles/benchmarks.html, but the main one won't be fixed until the next release, which will happen as soon as CRAN opens up again.

**Comment by jimhester** [comment]
Now fixed after 1.1.0 #200 has been released.
