### ISSUE TITLE
Inconsistent reading of large, irregular CSVs

### ISSUE THREAD

**Issue by dwachsmuth** [r-lib/vroom#212]
I have a series of very large (100-million to 10-billion row) CSVs I need to read into R, and I have found serious inconsistencies between how they are handled in readr::read_csv and vroom. No reprex for the moment, but here are the results:

Using the smallest of these files, I have the identical file in .csv and compressed in .gz.

- In both cases, read_csv("file.csv") or read_csv("file.gz") returns a table with 95,196,340 rows.
- For the uncompressed version, vroom("file.csv", delim = ",") returns a table with 89,567,376 rows.
- For the compressed version, vroom("file.gz", delim = ",") returns a table with 46,354,512 rows.

In the terminal, `cat file.csv | wc -l` returns 95,196,347 lines. So read_csv is successfully reading them all, give or take a few which are in fact corrupted, while vroom is failing to read about 7% of rows in the uncompressed file and 52% of rows in the compressed file.

The only obvious (to me) candidate for explaining this discrepancy is that the files are irregular, with most rows missing the final column. read_csv notes this with the usual warning about parsing failures, while vroom is silent. (Both functions succeed in reading the irregular column.)

I would love to be able to use vroom for this data, particularly because the larger files cannot be read in a single go with read_csv because they are too large (https://github.com/tidyverse/readr/issues/1073). But I'm currently prevented from doing so by this issue, and any feedback would be appreciated.

**Comment by jimhester** [comment]
Please make sure you have the latest version of vroom, this sounds like https://github.com/r-lib/vroom/issues/122

Otherwise if your file contains embedded newlines in fields make sure you set `num_threads = 1`.

**Comment by dwachsmuth** [comment]
Hi @jimhester,

I am running vroom 1.2.0, and I've gathered a bit more information about what's happening here. Focusing just on the raw CSV, not the gzipped version:

The num_threads argument changes the number of imported rows, but does not solve the issue:

- read_csv("data/daily_2014") produces 95,196,340 rows.
- vroom("data/daily_2014", delim = ",", num_threads = 32) produces 89,567,376 rows.
- vroom("data/daily_2014", delim = ",", num_threads = 1) produces 46,354,546 rows.

I can confirm that the issue appears to be related to the rows with missing columns. Because if I export the table with write_csv (after having successfully imported the entire thing with read_csv), then vroom successfully imports all the rows.

Also, vroom does not appear to be importing the first n rows and then failing, but rather is missing ranges within the total. E.g., the final row successfully imported by vroom (row index position 89,567,376) corresponds to row index position 94,197,319 in the full table imported by read_csv.

**Comment by jimhester** [comment]
My guess is a there is a field in the file with mismatched quotes, try setting `quote = ""` to disable quoting and see if that changes things.

**Comment by dwachsmuth** [comment]
Thanks, setting quote = "" did allow the entire file to be read successfully, so it looks like your guess is right.

Unfortunately, this is a situation where the cure was just as bad as the disease, since then I'm left with fields with superfluous quotation marks, and removing them with regex requires the entire field contents to be read, which means the whole process ends up slower using vroom than using read_csv:

- read_csv takes 2:11 to import the file.
- vroom takes only 4 seconds to import the file (insanely fast!), but the time to get the fields properly parsed with str_replace_all means that the whole process ends up being 7:30, so almost four times as slow.

A perfect world would be vroom's speed and read_csv's ability to catch row errors gracefully, but at least it's good to understand why vroom is struggling with this file. (data.table's fread segfaults with it, so that's even worse.)

**Comment by jimhester** [comment]
Ok, I will track this problem at https://github.com/r-lib/vroom/issues/212, so will close this issue.
