### ISSUE TITLE
pkgdown misconfiguration

### ISSUE THREAD

**Issue by hadley** [r-lib/vroom#216]
https://vroom.r-lib.org/index.html#reading-multiple-files — click on `vroom()` in `vroom::vroom` — it takes you to rdrr instead of the current site

**Comment by jimhester** [comment]
Ok, and how is this fixed?

**Comment by hadley** [comment]
I think maybe it's not supposed to have a host prefix? But I'm not even sure why it's getting linked outside in the first case.

**Comment by hadley** [comment]
Hmmm, this definitely works ok for pkgdown itself: https://pkgdown.r-lib.org/dev/#usage

And the generated yaml (https://pkgdown.r-lib.org/dev/pkgdown.yml vs https://vroom.r-lib.org/dev/pkgdown.yml) looks fine.

I've re-read the underlying pkgdown auto-linking code and I can't see anything wrong with it (I added a couple of tests just to make sure it works the way I thought).

Maybe try updating to the latest pkgdown workflow so you get the dev version? (Maybe it's a bug in the branch you're using?)

**Comment by jimhester** [comment]
Ok, I will try with the current dev version.

**Comment by jimhester** [comment]
The dev vroom site (<https://vroom.r-lib.org/dev>) has the right links, and building on the master branch works as well. But any build off of the `v1.2.0` tag, even re-building the site locally seems to contain the rdrr links.

**Comment by hadley** [comment]
The v1.2.0 tag of vroom?

**Comment by jimhester** [comment]
yeah

**Comment by hadley** [comment]
Duplicate of https://github.com/r-lib/pkgdown/issues/1262
