### ISSUE TITLE
Truncated data with CRLF newlines and no newline at end of file

### ISSUE THREAD

**Issue by jennybc** [r-lib/vroom#219]
Discovered in my googlesheets4 adventures.

Write this into `foo.csv` WITH NO TRAILING NEWLINE (which I realize is bad, but it's how Google Sheets CSV exports work):

```
X,Y
1,2016-12-08
```

Notice how the last cell is read correctly in the first case, but is `NA` in the second.

``` r
library(vroom)
vroom("foo.csv")
#> Rows: 1
#> Columns: 2
#> Delimiter: ","
#> dbl  [1]: X
#> date [1]: Y
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
#> # A tibble: 1 x 2
#>       X Y         
#>   <dbl> <date>    
#> 1     1 2016-12-08

vroom("foo.csv", col_types = cols(Y = col_date("%m/%/%Y")))
#> # A tibble: 1 x 2
#>       X Y         
#>   <dbl> <date>    
#> 1     1 NA
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jimhester** [comment]
I can reproduce this, but only if I explicitly specify the type as a date with a format. Using the default date format works fine.

``` r
writeBin(charToRaw("X,Y\n1,2016-12-08"), "foo.csv")
library(vroom)
vroom("foo.csv")
#> Rows: 1
#> Columns: 2
#> Delimiter: ","
#> dbl  [1]: X
#> date [1]: Y
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
#> # A tibble: 1 x 2
#>       X Y         
#>   <dbl> <date>    
#> 1     1 2016-12-08
vroom("foo.csv", col_types = cols(Y = col_date("%m/%/%Y")))
#> # A tibble: 1 x 2
#>       X Y         
#>   <dbl> <date>    
#> 1     1 NA
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Oh er what did you mean for the date to look like in this case? The format you pass is `%m/%/%Y`, but the date is formatted like `%Y-%m-%d`?

**Comment by jimhester** [comment]
And actually I cannot reproduce it if the date is formatted as the format string expects, with `%m/%d/%Y`

``` r
writeBin(charToRaw("X,Y\n1,12/08/2016,2,05/01/2018"), "foo.csv")
library(vroom)
vroom("foo.csv", col_types = cols(Y = col_date("%m/%d/%Y")))
#> # A tibble: 2 x 2
#>       X Y         
#>   <dbl> <date>    
#> 1     1 2016-12-08
#> 2     2 2018-05-01
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Ok so the issue is windows newlines + no trailing newline in the file. e.g.

``` r
writeBin(charToRaw("X,Y\r\n1,12/08/2016\r\n2,05/01/2018"), "foo.csv")
library(vroom)
vroom("foo.csv", col_types = cols(Y = col_date("%m/%d/%Y")))
#> # A tibble: 2 x 2
#>       X Y         
#>   <dbl> <date>    
#> 1     1 2016-12-08
#> 2     2 NA
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
We seem to have a general off by one error when there is no newline at the end of the file with windows newlines, e.g. the field is truncated below.

``` r
writeBin(charToRaw("X,Y\r\n1,12/08/2016\r\n2,05/01/2018"), "foo.csv")
library(vroom)
vroom("foo.csv", col_types = cols(Y = "c"))
#> # A tibble: 2 x 2
#>       X Y         
#>   <dbl> <chr>     
#> 1     1 12/08/2016
#> 2     2 05/01/201
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
