### ISSUE TITLE
Malformed date format leads to C stack usage error and/or segmentation fault

### ISSUE THREAD

**Issue by jennybc** [r-lib/vroom#220]
Discovered while fiddling with #219. A malformed date format in `col_date()` leads to this C stack usage error interactively and a seg fault when I try to show via `reprex::reprex()`. Even in the interactive case, the session often seg faults shortly thereafter.

``` r
> writeBin(charToRaw("Name,Date of death\nPat Summit,6/28/2016"), "foobar.csv")
> library(vroom)
> vroom("foobar.csv", col_types = cols(`Date of death` = col_date("%m/%/%Y")))
Error: C stack usage  17587313968752 is too close to the limit                   0s
```

**Comment by jimhester** [comment]
This seems to be a combination of a couple of issues.

1. `Rcpp::exception()` unconditionally calls `rcpp_set_stack_trace()` even though it is not needed when `include_call = false`. And `rcpp_set_stack_trace()` fails if called on a child thread. 
2. vroom uses `std::thread()` and I am not currently handling exceptions thrown by child threads, so they crash the process. Doing something like suggested in \#13 in https://www.acodersjourney.com/top-20-cplusplus-multithreading-mistakes/ is a way to fix this.

**Comment by jimhester** [comment]
But the short term solution to this issue is don't do that :-)

**Comment by jimhester** [comment]
Thank you for opening the issue and for supplying a reproducible example, it is a big help!
