### ISSUE TITLE
Suggestion: please add a new argument for assigning the 1st column to rownames

### ISSUE THREAD

**Issue by maomaowei5655** [r-lib/vroom#222]
### Suggestion: 
Please add a new argument for assigning the 1st column to rownames. 
Alternatively, please modify "_col_names_" (the argument in vroom()) as "_header_" (the argument in read.table()/read.csv(), cf. figure: 
<img width="429" alt="read table_intelligent_header_argument" src="https://user-images.githubusercontent.com/51223743/77741438-dcf51d00-704f-11ea-9bf2-a485d3e41a94.png">)
, which is set to TRUE **AND** the 1st column will be assigned to rownames **if the first row contains one fewer field than the number of columns** –– a usual format in molecular biological data (e.g. gene expression data, cf. files: [gene_expression_data.txt](https://github.com/r-lib/vroom/files/4392523/gene_expression_data.txt)→figure: 
<img width="348" alt="gene_expression_data-4sample_5column" src="https://user-images.githubusercontent.com/51223743/77741188-7112b480-704f-11ea-933c-38a5126d5250.png">).

--------------------------------BREAK--------------------------------------
read.table()/read.csv() can do well for data in the above format, but vroom() cannot:  
[outsideChina(Dropbox)→R_vroom_gene expression data.html](https://www.dropbox.com/s/q44mhm9djluc17n/R_vroom_gene%20expression%20data.html?dl=0)
[withinChina(坚果云)→R_vroom_gene expression data.html](https://www.jianguoyun.com/p/DVOAicYQkrGgCBicyYAD)
<img width="924" alt="read table_OR_read csv" src="https://user-images.githubusercontent.com/51223743/77812396-fe034f80-70db-11ea-874d-87e385c47d67.png">
<img width="928" alt="vroompng" src="https://user-images.githubusercontent.com/51223743/77812404-08254e00-70dc-11ea-8e25-fb4d1a200f97.png">

### Platform: 
macOS Catalina 10.15.1
RStudio Version 1.2.5033
R version 3.6.2
vroom version 1.2.0

**Comment by kiernann** [comment]
Tidy data frames typically don't use row names. See [chapter 3.6.2 of _Advance R_](https://adv-r.hadley.nz/vectors-chap.html#rownames) for an explanation.
It's simpler to just use a column. If you really need row names, try `tibble::column_to_rownames()` after reading.
