### ISSUE TITLE
csv read error with accented colname

### ISSUE THREAD

**Issue by ericemc3** [r-lib/vroom#223]
Hello,

this works
x <- readr::read_delim( "http://tiny.cc/8oiamz", delim=";", skip = 1 )

this yields an error : Error in nchar(x, "width") : invalid multibyte string, element 1  
x <- vroom::vroom("http://tiny.cc/8oiamz", delim=";", skip = 1 )

The specifics of the input file are:
- win-1252 encoding
- duplicated header row
- one column name with an accented character

**Comment by jimhester** [comment]
You need to specify the encoding if it is non UTF-8. The fact that this "works" in readr is actually a bug in readr and that your native encoding is likely 1252.

The following seems to read the file fine, I think this is working as designed.

``` r
vroom::vroom("http://tiny.cc/8oiamz", skip = 1, locale = vroom::locale(encoding = "CP1252"))
#> Rows: 105,863
#> Columns: 8
#> Delimiter: ";"
#> chr [4]: Communes, Codes_Insee, Numéro_département, DTREF
#> dbl [4]: NB_enfant_ARS, ARS_5A10, ARS_11A14, ARS_15A17
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
#> # A tibble: 105,863 x 8
#>    Communes Codes_Insee Numéro_départem… DTREF NB_enfant_ARS ARS_5A10 ARS_11A14
#>    <chr>    <chr>       <chr>            <chr>         <dbl>    <dbl>     <dbl>
#>  1 RESIDEN… 99999       <NA>             31/1…          1575      757       509
#>  2 COMMUNE… XXXXX       <NA>             31/1…           250       94        96
#>  3 L'ABERG… 1001        1                31/1…            40       12        19
#>  4 L'ABERG… 1002        1                31/1…            25        8         9
#>  5 AMBERIE… 1004        1                31/1…          1492      671       494
#>  6 AMBERIE… 1005        1                31/1…           110       52        37
#>  7 AMBLEON  1006        1                31/1…            NA       NA        NA
#>  8 AMBRONAY 1007        1                31/1…           200       96        64
#>  9 AMBUTRIX 1008        1                31/1…            42       20        14
#> 10 ANDERT … 1009        1                31/1…            19        9        NA
#> # … with 105,853 more rows, and 1 more variable: ARS_15A17 <dbl>
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ericemc3** [comment]
Thank you, it works indeed, i will use it.

Ideally i'd like vroom to detect automatically the proper encoding, but maybe it is not possible.

Or at least issue a warning "check the file encoding" or a more explicit message than 
Error in nchar(x, "width") : invalid multibyte string, element 1

**Comment by DiabbZegpi** [comment]
I have the same issue, with accented colnames and readr. I have used `readr::locale(encoding = "CP1252")` instead of vroom' and worked fine. Thanks @jimhester for your solution.

> You need to specify the encoding if it is non UTF-8. The fact that this "works" in readr is actually a bug in readr and that your native encoding is likely 1252.
