### ISSUE TITLE
CSV read error, truncating value

### ISSUE THREAD

**Issue by NeuroShepherd** [r-lib/vroom#226]
Vroom is truncating the 'a' off of the very last letter in a csv file. See below:

```
data_readr <- read_csv("iris_data.csv")
table(data_readr$Species)
setosa versicolor  virginica 
        50         50         50 

data_vroom <- vroom::vroom("iris_data.csv", delim = ",")
table(data_vroom$Species)
   setosa versicolor   virginic  virginica 
        50         50          1         49 
```
I manually confirmed the missing 'a' is from the last row/column in the data table, as well. Am I doing something wrong, possible encoding error, or a genuine bug?

**Comment by jimhester** [comment]
This is most likely a duplicate of https://github.com/r-lib/vroom/issues/219
