### ISSUE TITLE
`vroom_write` inherits wrong documentation for `col_names` parameter

### ISSUE THREAD

**Issue by jcblum** [r-lib/vroom#230]
Looks like `vroom_write` is inheriting the `col_names` parameter documentation from `readr::read_delim` (via inheriting from `vroom::vroom`), instead of from `readr::write_tsv`. 

These `roxygen2` tags:
https://github.com/r-lib/vroom/blob/488030af21cf9dff6e2aa91df346899397888cdc/R/vroom_write.R#L3-L4

https://github.com/r-lib/vroom/blob/488030af21cf9dff6e2aa91df346899397888cdc/R/vroom.R#L8

Add up to this documentation for `col_names`:
https://github.com/r-lib/vroom/blob/488030af21cf9dff6e2aa91df346899397888cdc/man/vroom_write.Rd#L31-L44

The upshot is incorrect documentation of `col_names` for `vroom_write`, since `readr::read_delim` allows passing a vector of column names in addition to `TRUE` or `FALSE`, while `vroom_write` doesn't.

If you take the above documentation at its word, the following should work (but obviously doesn't):

``` r
library(vroom)
out_file <- tempfile(fileext = ".tsv")
vroom_write(mtcars, out_file, col_names = paste0("col", 1:11))
#> Error in vroom_write_(xx, path, delim, na_str = na, col_names = col_names, : Expecting a single value: [extent=11].
```

(As a side note, it's also a bit confusing, since the `readr::read_delim` documentation for `col_names` refers to a whole bunch of things that don't really make sense in the context of writing a file)

**Comment by jimhester** [comment]
Thanks, should now be fixed!
