### ISSUE TITLE
Formatting datetime col_type issue and extra "\r" included in last column

### ISSUE THREAD

**Issue by j-sirgo** [r-lib/vroom#231]
I have several txt files reading vroom.
Each txt file has seven columns with skipped rows between each line (consecutive new line after contents of last column).

Vroom returns a “\r” at the end of the contents of column 7.  Is there a way to avoid this in vroom?  I know I can gsub the "\r" after, but that defeats the elegance and speed of vroom

Also the fifth column is a date time with format “%b %d, %Y@%H:%M” so I try the col_types argument with X5=col_datetime(format=“%b %d, %Y@%H:%M”) and vroom returns all missing despite having class POSIXct POSIXt.

Any options in vroom to correct these two issues within vroom?
I know I can read as character then convert as.POSIXct(X5, format=("%b %d, %Y@%H:%M")) but that defeats the elegance and speed of vroom.

**Comment by j-sirgo** [comment]
I resolved the datetime issue.  I needed another space before the %Y.

The “\r” issue remains.  I suppose this happens because each row in the source data has skips so two consecutive new lines.  How to omit these?

**Comment by j-sirgo** [comment]
Spoke too soon.   Looks like some time stamps have seconds and others don’t.  If I specify format=("%b %d, %Y@%H:%M") then the entries with seconds become missing values.  If I specify format=("%b %d, %Y@%H:%M:%S") then the entries without seconds become missing values.  Any way to address this in vroom?

**Comment by jimhester** [comment]
I am not really going to be able to help you without an example file.

**Comment by j-sirgo** [comment]
Ok - here is a working example:

Libraries needed:
`library(vroom)
library(dplyr)
library(lubridate)`

This issue is the data are separated by newlines and carriage returns.  Here I create an example called "test.txt":

`writeBin('\r\r\na^SEP 30, 2008@15:09^b\r\r\nc^APR 15, 2010@12:50:09^d\r\r\ne^JUN 21, 2018@08:20^f', "text.txt")`

Reading in vroom (with no seconds on datetime format):
 
`vroom("text.txt", delim="^", col_names=FALSE, skip=1,col_types=cols(X1=col_character(),X2=col_datetime(format="%b %d, %Y@%H:%M"),X3=col_character()))`
                                                                                                                                                                                         
  X1    X2                  X3   
  <chr> <dttm>              <chr>
1 a     2008-09-30 15:09:00 "b\r"
2 c     NA                  "d\r"
3 e     2018-06-21 08:20:00 "f"  

The result is the 2nd row's date is missing and you see the carriage return in the X3 (not for the last row).

I can read in vroom with seconds on datetime format:

`vroom("text.txt", delim="^", col_names=FALSE, skip=1,col_types=cols(X1=col_character(),X2=col_datetime(format="%b %d, %Y@%H:%M:%S"),X3=col_character()))`
                                                                                                                                                                                       
  X1    X2                  X3   
  <chr> <dttm>              <chr>
1 a     NA                  "b\r"
2 c     2010-04-15 12:50:09 "d\r"
3 e     NA                  "f"  

The result is the 1st and 3rd row's date is missing and you see the carriage return in the X3 (not for the last row).

I can read all as character in vroom, then use lubridate::parse_date_time to look for both datetime formats and use sub() to eliminate instances of carriage return "\" but the speed of the process slows down as a result of processing the data in dplyr after vroom.
 
`vroom("text.txt", delim="^", col_names=FALSE, skip=1) %>% mutate(X2=parse_date_time(X2,orders=c("%b %d, %Y@%H:%M","%b %d, %Y@%H:%M:%S")),X3=sub("\\r[\\s\\S]*", "", X3))`

  X1    X2                  X3   
  <chr> <dttm>              <chr>
1 a     2008-09-30 15:09:00 b    
2 c     2010-04-15 12:50:09 d    
3 e     2018-06-21 08:20:00 f

**Comment by jimhester** [comment]
This is a profoundly weird file.

f6bbd9125b73359f26f6f extends the whitespace trimming to `\r` characters which handles the issue with the third column.

Using the [flexible HMS parser](https://readr.tidyverse.org/reference/parse_datetime.html#format-specification) allows you to handle the variable seconds in the second column.

After this the file seems to be read as you desire.

``` r
writeBin("\r\r\na^SEP 30, 2008@15:09^b\r\r\nc^APR 15, 2010@12:50:09^d\r\r\ne^JUN 21, 2018@08:20^f", "text.txt")
library(vroom)
vroom("text.txt", delim = "^", col_names = FALSE, skip = 1, col_types = list(X2 = col_datetime(format = "%b %d, %Y@%AT")))
#> # A tibble: 3 x 3
#>   X1    X2                  X3   
#>   <chr> <dttm>              <chr>
#> 1 a     2008-09-30 15:09:00 b    
#> 2 c     2010-04-15 12:50:09 d    
#> 3 e     2018-06-21 08:20:00 f
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by j-sirgo** [comment]
Many thanks.

How does “f6bbd9125b73359f26f6f” get implemented?  Uninstall and reinstall vroom?

**Comment by j-sirgo** [comment]
Sorry to be a pest, but I tried:

`devtools::install_dev("vroom")`

and still getting the '\r'

Will it be updated on CRAN?

**Comment by j-sirgo** [comment]
Never mind.  Got 1.2.1 and works.
Many thanks
