### ISSUE TITLE
append=TRUE destroys data file if path has compression extension

### ISSUE THREAD

**Issue by cboettig** [r-lib/vroom#232]
```r
path <- "test.tsv.gz"
df <- data.frame(A = 1, B = 2)
vroom::vroom_write(df, path)
vroom::vroom_write(df, path, append=TRUE)
vroom::vroom(path)
```

boom, rows are all gone:

```
Rows: 0                                                                                                                                                                    0s
Columns: 2
Delimiter: "\t"
chr [2]: 1, 2
````

If we use an uncompressed path extension (e.g. just make `path = "test.tsv"), then things work as expected.  `readr` and base R are both fine when appending to a compressed file / connection as well.  

We get the same error on `vroom` if we explicitly create the connection with `file(path)` and pass that to `vroom` too.

**Comment by jimhester** [comment]
Fixed by 59bc555740718714a4b
