### ISSUE TITLE
Argument "na" does not work with Cyrillic characters

### ISSUE THREAD

**Issue by shmelee** [r-lib/vroom#233]
Hello! Argument "na" does not work with cyrillic characters:

```r
vroom(file, ";", FALSE, n_max = 48 * 3, locale = locale(decimal_mark = ",", encoding = "UTF-8"), 
            na = "Нет данных")
```
_v. 1.2.0.9000_

[РСВ_Группа_ЕГО_для_ВСВГО_362210_13.05.2020.zip](https://github.com/r-lib/vroom/files/4614737/_._._._._362210_13.05.2020.zip)

**Comment by jimhester** [comment]
The `na` argument needs to be in UTF-8, so a workaround for the CRAN version of vroom is to use `na = enc2utf8("Нет данных")`
