### ISSUE TITLE
Comment lines after real data begins are not removed

### ISSUE THREAD

**Issue by klattery** [r-lib/vroom#241]
Rows beginning with comment characters are removed when they are at the top of the file.  But later comments in rows after some data are not removed.  See attached csv (as .txt) for simple example.  The first two rows are removed but not the later rows. 
x <- vroom(file,
           delim =",",col_types = c(.default = "d"),
           comment = "#")
[vroom_test2.txt](https://github.com/r-lib/vroom/files/4776600/vroom_test2.txt)

**Comment by jimhester** [comment]
Yes, this is unfortunately the way the parser works. It is unlikely to change. I would suggest removing these comment lines in a preprocessing step if needed.
