### ISSUE TITLE
vroom generates large temporary files that are not deleted

### ISSUE THREAD

**Issue by lucasmation** [r-lib/vroom#242]
I am trying to investigate some large files (20 to 100 million observations) using `vroom_lines` on a Windows computer (a server to which I remote access)

```
library(tidyverse)
library(vroom)

fs <- list.files()
for( f in fs){
   vroom_lines(altrep=T,progress=T) %>% lenght %>% print
}
```

As `vroom_lines` runs the available space in disc `C:` (windows base disk) keeps decreasing quickly until it eats all 36.5Gb of disk space. In the loop above, after `vroom_line` concludes the first iteration of the loop the disk use does not decrease. If I interrupt the R session disk use also is only partially reduced. Finally, only if I sign out of the server the disk space in `C:` is restored. Therefore I am assuming that only by signing out the temporary files are deleted.

UPDATE: I just checked  `tempdir() %>% list.files` after running  `vroom_lines` in a 0.8Gb file. The command leaves behind a 10Gb tempfile after execution has stopped.

UPDATE2: `tempdir %>% list.files(full_paths=T) %>% file.remove` returns an error message saying I don't have permission to remove the file. So part of the problem may be specific to the server user permissons. However such a large temp-file is weird.

Also. the file being read is of fwf  (position delimited) type.

UPDATE3: I initially diagnosed this with `vroom_lines` but the `vroom` function also generates very large temporary files.

**Comment by jimhester** [comment]
If you are passing in compressed files or R connections these need to be uncompressed to temporary files to be read. They are cleaned up when the objects holding handles to them are garbage collected. If you are unable to delete temporary files in your default temp directory you can set the [`VROOM_TEMP_PATH` environment variable](https://github.com/r-lib/vroom#environment-variables) to whatever directory you would prefer they are written into.

**Comment by lucasmation** [comment]
@jimhester tks. You are correct, I am reading a 3.8Gb `.bz2` file. For future reference, this solves the problem

`Sys.setenv(VROOM_TEMP_PATH = 'E:/myspaciousdirectory')`

After that,  `vroom_lines(alrep=T)` on this file works. It takes 25min and generates an 80Gb tempfile in `'E:/myspaciousdirectory'. This file is not deleted after  `vroom_lines` concludes reading.

**Comment by yonparas** [comment]
@jimhester Hi Jim, are there any fixes for this yet? I still am seeing vroom generated files in the Temp folder that are not being deleted even after restarting the RStudio that holds these objects.

**Comment by jimhester** [comment]
I don't believe there is anything to fix. The files should be deleted automatically once the objects are garbage collected, e.g.

``` r
library(vroom)

x <- vroom(file(vroom_example("mtcars.csv.gz")))
#> Rows: 32 Columns: 12
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (1): model
#> dbl (11): mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
list.files(tempdir())
#> [1] "vroom-944655c18ad7"

rm(x)
gc()
#>           used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
#> Ncells  715431 38.3    1393844 74.5         NA  1393844 74.5
#> Vcells 1329216 10.2    8388608 64.0      32768  1992393 15.3
list.files(tempdir())
#> character(0)
```

<sup>Created on 2021-09-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tbarchyn** [comment]
The above reprex doesn't delete the tempfile on my version of windows here.

I'll report back if I can figure out why (and its probably upstream from vroom), but for now I've gone to manually deleting the vroom tempfiles.

Windows 10 Version	10.0.19043 Build 19043
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)
vroom_1.5.7
```
library(vroom)

x <- vroom(file(vroom_example("mtcars.csv.gz")))
#> Rows: 32 Columns: 12
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (1): model
#> dbl (11): mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
list.files(tempdir())
#> [1] "vroom-5644508a1b"

rm(x)
gc()
#          used  (Mb) gc trigger  (Mb) max used  (Mb)
#Ncells 2433244 130.0    3670861 196.1  3670861 196.1
#Vcells 6202471  47.4   12255594  93.6  8692029  66.4

list.files(tempdir())
#> [1] "vroom-5644508a1b"
```

**Comment by GBarnsley** [comment]
I've also been having the same issue @tbarchyn. On Windows 10, R version 4.2.1, vroom 1.5.7.
Thanks for the temporary fix, though if you're still having the same issue, it might worth opening a new GitHub issue on this?
