### ISSUE TITLE
vroom fails to see the value in a column of 495704 rows

### ISSUE THREAD

**Issue by genghiskhanofnz** [r-lib/vroom#243]
Hi there, thanks for your vroom.  I really like it because it is fast.
I am now working with vroom everyday.
But, today, it fails.  It fails to read the value in a column of 495704 rows dataframe imported csv.
It is a pathology file real world data.
The column contains 2 values = blank and VPAS
blanks length = 495704 minus 30
VPAS length = 30

Well, so, i imported as fread from data.table.
Then, I do
pathology_datatable %>% 
  filter(VPAS == 'VPAS') %>% 
  select(UrNumber, VPAS, `Cost Centre`)

The data.table could see all 30 of VPAS values under VPAS column.

Please advise why vroom did not import and see the value in that column.
Thanks.

**Comment by jimhester** [comment]
Could you provide a [reproducible example](https://www.tidyverse.org/help/) that illustrates the issue.

**Comment by genghiskhanofnz** [comment]
my R code after importing path_janjun2020_vroom_2col.txt
change to txt file for you.
i use csv extension.
The file attached as txt.
Thanks.
[path_janjun2020_vroom_2col.txt](https://github.com/r-lib/vroom/files/4848645/path_janjun2020_vroom_2col.txt)




# vroom reproducible e.g.
pathvroom <- vroom('Z:\\path_janjun2020_vroom_2col.csv')
head(pathvroom)

tail(pathvroom, 25)

pathvroom[495680:495704, ]

# vroom fails to see the value VPAS under the VPAS column from the row 495689 to 495701

pathvroom %>% 
  filter(VPAS == 'VPAS') %>% 
  select(`Cost Centre`, VPAS)

# > pathvroom %>% 
#   +   filter(VPAS == 'VPAS') %>% 
#   +   select(`Cost Centre`, VPAS)
# # A tibble: 0 x 2
# # ... with 2 variables: `Cost Centre` <chr>, VPAS <lgl>

**Comment by jimhester** [comment]
The issue is most of the column is missing, so the column type deduction is assuming the column is a logical column, rather than a character. Explicitly setting it as character gives you the behavior you were expecting.

``` r
x <- vroom::vroom("~/p/vroom/path_janjun2020_vroom_2col.txt", col_types = "cc")
tail(x)
#> # A tibble: 6 x 2
#>   VPAS  `Cost Centre`
#>   <chr> <chr>        
#> 1 VPAS  Y0602        
#> 2 VPAS  Y0602        
#> 3 <NA>  Y0602        
#> 4 <NA>  Y0602        
#> 5 <NA>  Y0252        
#> 6 <NA>  Y0602
x[495680:495704, ]
#> # A tibble: 25 x 2
#>    VPAS  `Cost Centre`
#>    <chr> <chr>        
#>  1 <NA>  Y0002        
#>  2 <NA>  Y0002        
#>  3 <NA>  Y0002        
#>  4 <NA>  Y0002        
#>  5 <NA>  Y0602        
#>  6 <NA>  Y0602        
#>  7 <NA>  Y0602        
#>  8 <NA>  Y0002        
#>  9 VPAS  Y0602        
#> 10 VPAS  Y0602        
#> # … with 15 more rows
```

<sup>Created on 2020-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
