### ISSUE TITLE
A date field crashes the R session when reading in with vroom

### ISSUE THREAD

**Issue by OssiLehtinen** [r-lib/vroom#254]
The latest development version of vroom seems to have an issue with dates.

The following crashes the R session:
```
df <- data.frame(a = Sys.Date())
write.csv(df, "tmp.csv")
vroom::vroom("tmp.csv", delim = ",")
```

This does not happen with the release-version (1.2.0 on my system at the moment)

**Comment by jimhester** [comment]
This should be fixed by https://github.com/r-lib/vroom/commit/b485fd79fb954d70f24da5e69c8da10464d83ee4

**Comment by OssiLehtinen** [comment]
Works on my box too. Thanks for the quick fix!
