### ISSUE TITLE
Language special characters not recognized 

### ISSUE THREAD

**Issue by GitHunter0** [r-lib/vroom#258]
Special characters of Portuguese language are not being read and displayed correctly. I tried to specify other encoding systems but the package only seems to support UTF-8.

```
vroom::vroom(
  "http://dados.cvm.gov.br/dados/FI/CAD/DADOS/inf_cadastral_fi_20200731.csv",   
  locale = locale(encoding = "UTF-8")
  ) 
```
Please, see row 1, column 6, for an example of the issue. 

Thank you

**Comment by jimhester** [comment]
That file is in latin-1 encoding.

``` r
library(vroom)

x <- vroom(
  "http://dados.cvm.gov.br/dados/FI/CAD/DADOS/inf_cadastral_fi_20200731.csv",
  locale = locale(encoding = "latin1")
)
#> Rows: 13,276
#> Columns: 36
#> Delimiter: ";"
#> chr  [24]: CNPJ_FUNDO, DENOM_SOCIAL, SIT, CLASSE, RENTAB_FUNDO, CONDOM, FUNDO_COTAS, FUNDO...
#> dbl  [ 3]: TAXA_PERFM, TAXA_ADM, VL_PATRIM_LIQ
#> date [ 9]: DT_REG, DT_CONST, DT_CANCEL, DT_INI_SIT, DT_INI_ATIV, DT_INI_EXERC, DT_FIM_EXER...
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
x[[6]][[1]]
#> [1] "FASE PRÉ-OPERACIONAL"
```

<sup>Created on 2020-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by GitHunter0** [comment]
Thank you @jimhester , where can I find a list with the supported encodings?

One issue occured, wroom is dropping a lot of observations, while this returns 37,980 rows

`data.table::fread("http://dados.cvm.gov.br/dados/FI/CAD/DADOS/inf_cadastral_fi_20200731.csv")`

This returns only 13,337 rows:
```
vroom::vroom( "http://dados.cvm.gov.br/dados/FI/CAD/DADOS/inf_cadastral_fi_20200731.csv",  
                        locale = locale(encoding = "latin1") ) 
```

**Comment by jimhester** [comment]
There is an embedded quote in the file, use `quote = ""` to disable quoting.

**Comment by GitHunter0** [comment]
@jimhester I appreciate the hints, it solved the problem.
