### ISSUE TITLE
Request alternate line endings capability

### ISSUE THREAD

**Issue by mb147** [r-lib/vroom#263]
Vroom is writing LF EOL for me, but I need CRLF EOL.
There seems to be no option to request specific EOL in Vroom.

Could this please be added to give more flexibility?
Or, if it's already possible, could a note be added to documentation about how best to achieve this?

At the moment I'm reading with Vroom, but writing with data.table::fwrite because it exposes a line ending parameter.
Whilst that's ok as a workaround, I'd like to just use Vroom_write if possible.
My environment is RStudio on Windows - in case that influences Vroom behavior or dev response.

**Comment by jimhester** [comment]
Thanks, this should now be possible with the `eol` argument to `vroom_write()`.
