### ISSUE TITLE
Vroom issue with too many files (linux)

### ISSUE THREAD

**Issue by davidmasp** [r-lib/vroom#268]
When trying to read multiple files (10,000 files) in linux it raises a error saying that there are too many files open and then complains that one of the files doesn't have the same number of columns (which I am pretty sure it's not true). I already saw this issue #180 but the problem occurs in linux for my case while windows is fine. I don't have a Mac machine around so I couldn't check there.

```
mapping error: Too many open files
Error in vroom_(file, delim = delim %||% col_types$delim, col_names = col_names,  :
  Files must all have 2 columns:
* File 1018 has 0 columns
Calls: <Anonymous> -> vroom_
Execution halted
```

For what I know linux has a soft limit in the number of open files that can be checked with with `ulimit -Sn` (see [this](https://www.tecmint.com/increase-set-open-file-limits-in-linux/)). I did increase the limit to 12k files which should be sufficient to deal with the current problem and indeed it does workaround it. However I get another (unrelated?) issue. Not sure if this would be a valid workaround for me anyway because in some machines I don't have sudo so can be hard to change the system params.

```
Error: 'vec_as_names' is not an exported object from 'namespace:vctrs'
Execution halted
```

After updating the package `vctrs` it managed to run alight. I am not sure why it didn't update with vroom as this package is not loaded in the session info output of the linux devices but it does appear in the windows one. 

I set up a repo for reproducibility if useful. There are more details there that might be useful.

https://github.com/davidmasp/vroom_issue

**Comment by davidmasp** [comment]
I think `vctrs` didn't appear in the first `sessionInfo()` because it is only called after the vroom function. It does appear in the second indeed. I am not sure which version I had before but now I have `0.3.4` in my ubuntu and `vctrs_0.2.2` in windows when I manage to run it okay. Maybe vroom would need to require that version in the `DESCRIPTION` file? I think now it doesn't require any version ([here](https://github.com/r-lib/vroom/blob/e3338202aeecf8cf1914c231b35ca681133c26d6/DESCRIPTION#L50)).

**Comment by jimhester** [comment]
vroom holds a file handle to all the open files until the data is read from all of them, so this is working as intended.

It looks like the first vctrs release with `vec_as_names()` (which is the main thing vroom uses) is 0.2.0, so I added that to the DESCRIPTION.

**Comment by cboettig** [comment]
Also hit this regularly.  For reasons I don't understand, if I'm in RStudio and turn altrep off, I don't hit the file limit.  With altrep on in RStudio, I do get the error.   If I run the same command on cli R with altrep off, I also hit the error.  Running on Linux in both cases, and haven't tried adjusting the OS system limits (though thanks @davidmasp for the instructions for that!)

I don't suppose it would be possible for `vroom` to check the limit first and then iterate in max_files chunks?

**Comment by davidmasp** [comment]
np! I think I also tried with altrep=off but did not work. 

Indeed it would very helpful if it could be limited somehow with an argument. For my use case in a HPC system I can't change my open file limits unfortunately. Reaching 1k files in this scenario is rather common so it is really a pity. At least now I know the cause of the error so I can plan better.
