### ISSUE TITLE
vroom causes progress::progress_bar to flicker (in some cases)

### ISSUE THREAD

**Issue by cboettig** [r-lib/vroom#269]
Consider this example of iterating over vroom reading in a bunch of different files:

```r
setwd(tempdir())
library(vroom)

files <- paste0("dummy", 1:1880, ".csv")
x <- lapply(files, function(f) vroom_write(iris, f))
```

```r
pb <- progress::progress_bar$new(
  format = "  importing [:bar] :percent eta: :eta",
  total = length(files),
  clear = FALSE,
  width = 60,
  show_after = 0)


## progress bar FLICKERS off and on, unreadable
for(f in files){
  pb$tick()
  suppressMessages({
  df <- vroom(f)
  })
  
}
```

Compare to base R, no flickering:

```r
pb <- progress::progress_bar$new(
  format = "  importing [:bar] :percent eta: :eta",
  total = length(files),
  clear = FALSE,
  width = 60,
  show_after = 0)

for(f in files){
  pb$tick()
  suppressMessages({
    df <- read.csv(f)
  })
  
}
```

The issue seems to go away if I use a smaller number of files in the iteration.

**Comment by jimhester** [comment]
vroom uses a progress bar itself, run it with `vroom(progress = FALSE)`?

**Comment by cboettig** [comment]
Thanks (and thanks for the quick response)!  

I had tried turning it off with `options(readr.show_progress = FALSE)` but that didn't do the trick somehow.  using `progress=FALSE` seems to work.

**Comment by jimhester** [comment]
It doesn't use `readr.show_progress`, you can control it with the `VROOM_SHOW_PROGRESS` environment variable though if you want. https://github.com/r-lib/vroom#environment-variables
