### ISSUE TITLE
Consider cctz instead of R derived localtime

### ISSUE THREAD

**Issue by hadley** [r-lib/vroom#273]
e.g. https://github.com/DavisVaughan/rcctz

And `cctz::convert(cctz::civil_second(y, m, d, H, M, S), tz)` (from @DavisVaughan)

**Comment by DavisVaughan** [comment]
Probably would look something like this:
https://github.com/DavisVaughan/rcctzuser/blob/master/src/code.cpp

```r
> fun("America/New_York")
[1] "2020-01-05 01:01:01 EST"
> fun("America/Los_Angeles")
[1] "2020-01-05 01:01:01 PST"
```

**Comment by hadley** [comment]
Or better, https://github.com/HowardHinnant/date
