### ISSUE TITLE
Reading large character

### ISSUE THREAD

**Issue by marciz** [r-lib/vroom#274]
Issue with R 4.0.2
```
library(vroom)

n <- as.integer(2e7)
x <- data.frame(a = 1:n, b = n, c = n, d = n, e = n, f = n)

tfile <- tempfile()

# vroom_write(x = x, path = tfile)
write.csv(x = x, file = tfile)

system.time({
  vroom(file = tfile)
})
>  user  system elapsed 
>   16.47    2.40    3.86 

y <- readChar(con = tfile, nchars = 2e9)

system.time({
  vroom(file = y)
})
# this never finishes on R 4!!!

system.time({
  data.table::fread(input = y)
})
>    user  system elapsed 
>    5.83    0.12    2.02 

```
#270

**Comment by jimhester** [comment]
input from string literals is really only meant for examples and testing.

It just dumbly writes the string to a file and then vroom reads the file. It does remove the trailing newline if it exists with `sub()`, which would copy the vector, and likely causes the hang.

It is not designed in any way to be performant, so I don't think this is likely to be fixed.
