### ISSUE TITLE
vroom replacing missing values with literal "NA", not <NA>

### ISSUE THREAD

**Issue by JustGottaCAT** [r-lib/vroom#275]
As the title says, I'm using `vroom` to read a .tsv file with a number of empty columns and it is replacing all missing values with the literal string "NA" instead of an actual `<NA>` character. Is this supposed to be the case, and is it possible to change it? I have set `na = c("", " ", "NA")`.

**Comment by jimhester** [comment]
Can you provide a reproducible example, I cannot reproduce this.

``` r
vroom::vroom("a,b\n,1\nc,NA")
#> Rows: 2
#> Columns: 2
#> Delimiter: ","
#> chr [1]: a
#> dbl [1]: b
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
#> # A tibble: 2 x 2
#>   a         b
#>   <chr> <dbl>
#> 1 <NA>      1
#> 2 c        NA
```

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JustGottaCAT** [comment]
Sure, this is the exact dataset that I saw the issues with. I downloaded it with the following URL:
`https://opendata.usac.org/resource/avi8-svp9.tsv?$query=select%20*%20where%20funding_year%20=%20%272017%27%20and%20form_471_service_type_name%20=%20%27Voice%27%20and%20qty_allocation%20=%20%27%27%20limit%20999999999999&`

Any time a column was all blanks it returned "NA" for all rows.

**Comment by jimhester** [comment]
These seem to be the correct `NA_character_` values to me?

``` r
url <- "https://opendata.usac.org/resource/avi8-svp9.tsv"
library(vroom)
x <- vroom::vroom(url, na = c("", " ", "NA"), delim = "\t", col_types = cols(.default = 'c'), n_max = 10)
is.na(x$tribal_type)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JustGottaCAT** [comment]
I re-installed vroom and now it's working again. I could not tell you what changed as I had not messed with any profile or system options. Closing.
