### ISSUE TITLE
Install error on Ubuntu 18.04

### ISSUE THREAD

**Issue by sschloss1** [r-lib/vroom#277]
I'm running R 4.0.2 on Ubuntu 18.04. and I'm getting an error when I try to install vroom from CRAN (I get the exact same message when installing the dev version).

Here's the error message and the last few lines of the `install.packages` output.  I can post the rest if you need to see it.
```
/home/computer/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include/Eigen/src/Geometry/Quaternion.h:46:50:   required from ‘class Eigen::QuaternionBase<Eigen::Quaternion<double> >’
/home/computer/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include/Eigen/src/Geometry/Quaternion.h:232:7:   required from ‘class Eigen::Quaternion<double>’
/home/computer/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include/Eigen/src/Geometry/arch/Geometry_SSE.h:92:3:   required from here
/home/computer/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes]
                      >::type PacketReturnType;
                              ^~~~~~~~~~~~~~~~
/usr/lib/R/etc/Makeconf:176: recipe for target 'Iconv.o' failed
```

**Comment by jimhester** [comment]
vroom itself doesn't use RcppEigen, or even Rcpp, so this error must be coming from installing some dependency which does. You will need to include more the the output, but in any case this is unlikely to be an issue in vroom.

**Comment by sschloss1** [comment]
You're right.  I started a clean R session and the install worked perfectly.  Must've been something going on with a loaded package.  Thanks for the quick response.
