### ISSUE TITLE
Unique gen_name() values

### ISSUE THREAD

**Issue by aosavi** [r-lib/vroom#279]
I noticed that the `gen_name` function does not necessarily return unique values: `length(unique(gen_name(1000)))` is often < 1000. Would it be possible to add unique values as an option?

**Comment by jimhester** [comment]
I don't think I would want to add an option for it, but you can write a function that returns only unique values with this.

```r
unique_gen_name <- function(n) {
  x <- vroom::gen_name(n)
  dups <- duplicated(x)
  while(any(dups)) {
    x[dups] <- vroom::gen_name(sum(dups))
    dups <- duplicated(x)
  }
  x
}
```
