### ISSUE TITLE
Vroom comment cannot differentiate lines starting with ## and #

### ISSUE THREAD

**Issue by liutiming** [r-lib/vroom#286]
Thanks for the hard work!

I have a file (vcf in bioinformatics) with comments starting with ## and column headers starting with #. When using vroom to read the file, both comments and headers will be removed regardless whether the comment parameter was set as `##` or `#`. `read_tsv` can recognize the difference.

**Comment by jimhester** [comment]
Thank you for opening the issue, this should now be possible.
