### ISSUE TITLE
Unable to write file with no separator between 

### ISSUE THREAD

**Issue by tjcason** [r-lib/vroom#287]
I have an API I need to provide data to in a fixed with format that I had been using write.table for that vroom would likely be MUCH faster for, but I am unable to get "" as my separator, it corrects it to a space which then makes my output file too wide. 
Here's a reprex: 

```{r}
library(tidyverse) #Load 
data("iris") #Load Dataset
#My API requires each field to be 7 characters long
iris %>%
  mutate(Species = str_pad(string = substr(Species, start = 1, stop = 7), width = 7, side = "right", pad = " ")) %>% 
  mutate_if(is.numeric, ~str_pad(string = as.character(.*100), width = 7, side = "left", pad = "0")) %>% 
  vroom::vroom_write(path = "pathtomydata.txt", delim = "", na = "", col_names = FALSE, append = FALSE, bom = FALSE)
```

Even though I set the delimiter to be "" it still throws a space between them. 
![image](https://user-images.githubusercontent.com/53591368/103230744-cf7d0400-48fb-11eb-8651-46b65e2ffed3.png)

**Comment by jimhester** [comment]
Thanks, should be fixed now.
