### ISSUE TITLE
Escape double = TRUE slower than readr and crashing.

### ISSUE THREAD

**Issue by Eflores89** [r-lib/vroom#288]
I have a 2.7GB dataset with "quirky" characters (e.g., "\T" in some description fields). When reading with readr (foo_1) with escape_double = F, from an S3 bucket I have a long waiting time but it is stable. When running the "same" function in vroom (foo_2), R hangs (taking up 10x times to read) and then crashes:

```
foo_1 <- function(x){
  readr::read_delim(x, "\t", escape_double = FALSE, locale = locale(), trim_ws = TRUE)
}

foo_2 <- function(x){
  vroom::vroom(x, delim = "\t", escape_double = FALSE, locale = locale(), trim_ws = TRUE)
}


# importing from S3 bucket (long time, but stable)
d <- aws.s3::s3read_using(foo_1, 
                           object = file, 
                           bucket = "my-bucket") 

# importing from S3 bucket (crashes after hanging)
d <- aws.s3::s3read_using(foo_2, 
                           object = file, 
                           bucket = "my-bucket") 
```

Is this a known bug?

**Comment by Eflores89** [comment]
Upon further reviewing, the problem is in `locale = locale()`, my take is probably trying to load all the dataset in memory as opposed to altrep?

However, another issue surfaces: vroom cannot differentiate by case the delimiters. Original file has 15M rows, which is read correctly by readr, but only 8M are read with vroom (with corresponding mixed columns due to delimiters being badly parsed). Any work-around suggested or is the way parsing just totally different between both packages?

**Comment by jimhester** [comment]
The way parsing is done is totally different in vroom and readr, but you will have to provide a reproducible example for me to be able to tell what is going on.

I think it is likely completely unrelated to what you think the problem is.

**Comment by jimhester** [comment]
Also if you are up for it you may want to try with the development version of vroom, it has some additional features that may reveal the issue.
