### ISSUE TITLE
Current best practice for writing lines

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/vroom#291]
What's the current recommendation for quickly writing a vector to disk, similar to `vroom_write()` for data frames?

Obvious choices:
- `readr::write_lines()`: supports `append`, which is nice.
- `base::readLines()`.
- Note that data.table can do this with `fwrite()`, using `x = as.list(x)` and `sep = "\n"` as input.

If vroom is going to be used as a readr backend (see #282), will there be support for `write_lines()`?

**Comment by jimhester** [comment]
I actually implemented a `vroom_write_lines()` function yesterday, it is basically just this.

**Comment by mjsteinbaugh** [comment]
Sweet that's great. Thanks @jimhester !

**Comment by mjsteinbaugh** [comment]
@jimhester following up on this, I'm seeing errors with the CRAN version of vroom and the latest version on GitHub:

## vroom 1.4.0:

```r
vroom::vroom_write_lines(x = c("aaa", "bbb", "ccc"), path = "test.txt")
```

```
Warning in `[<-.data.frame`(`*tmp*`, , value = list(X1 = c("aaa", "bbb",  :
  replacement element 1 has 3 rows to replace 2 rows
Calls: <Anonymous> -> vroom_write -> [<- -> [<-.data.frame
Error: Expected string vector of length 1
```

## vroom 1.4.0.9000 (8709171):

```r
vroom::vroom_write_lines(x = c("aaa", "bbb", "ccc"), file = "test.txt")
```

```
Warning in `[<-.data.frame`(`*tmp*`, , value = list(X1 = c("aaa", "bbb",  :
  replacement element 1 has 3 rows to replace 2 rows
Calls: <Anonymous> -> vroom_write -> [<- -> [<-.data.frame
```

**Comment by jimhester** [comment]
Sorry about that, unfortunately we had to do a vroom release faster than we wanted because of a CRAN imposed deadline, and this function was included in a broken state. It should now be fixed.

**Comment by mjsteinbaugh** [comment]
Cool thanks @jimhester !
