### ISSUE TITLE
comment not work

### ISSUE THREAD

**Issue by yikeshu0611** [r-lib/vroom#294]
we use vroom to read the following data and we want to skip the third line because of it start with _ , so we use comment parameter, however it does not work
```r
vroom::vroom('x,y
             1,2
             2,3
             _2,3',delim=',',comment='\_')
# Return
# A tibble: 3 x 2
  x         y
  <chr> <dbl>
1 1         2
2 2         3
3 _2        3
```

**Comment by jimhester** [comment]
vroom doesn't support comments within data, only at the start of the file, so this is expected
