### ISSUE TITLE
How to suppress parsing problems

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/vroom#300]
When dealing with a file with known parsing issues, how do I suppress the `problems()` warning?

```r
packageVersion("vroom")
## [1] '1.4.0'
file <- "http://www.informatics.jax.org/downloads/reports/MGI_Gene_Model_Coord.rpt"
df <- vroom::vroom(file = file, delim = "\t")
print(df)
## Warning: One or more parsing issues, see `problems()` for details
attr(df, "problems")
## <pointer: 0x7f9cbda1b000>
probs <- vroom::problems(df)
print(probs)
```

**Comment by mjsteinbaugh** [comment]
See related unit tests in [`test-problems.R`](https://github.com/r-lib/vroom/blob/master/tests/testthat/test-problems.R)

**Comment by mjsteinbaugh** [comment]
This doesn't work:

```r
attr(x = df, which = "problems") <- NULL
print(df)
## Warning: One or more parsing issues, see `problems()` for details
```

**Comment by jimhester** [comment]
`suppressWarnings()`

**Comment by mjsteinbaugh** [comment]
@jimhester weird I tried that and it wasn't working in one case. I'll see if I can make a reprex and repost.

**Comment by mjsteinbaugh** [comment]
OK great seems like `suppressWarnings` is working for me. Looks like this is safe to close.
