### ISSUE TITLE
incorrect docs in vroom_write?

### ISSUE THREAD

**Issue by cboettig** [r-lib/vroom#304]
vroom_write documentation for `path` simply says "lifecycle deprecated".  Apparently it is inheriting this from `readr::read_tsv()`, where the `path` argument has been deprecated.  perhaps the intent was to inherit the argument known as `file` from `readr::read_tsv` (or `vroom`) instead?

(As an aside, I'm consulting said docs to find out why on Windows, `vroom_write(data, filepath)` is failing with an error "cannot open file for writing", while the same code passes on Mac and Linux, and passes with base R's `write.csv`)

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/vroom/commit/e9003b44c9c5d5a3df97faf40760871a39ad8117
