### ISSUE TITLE
`vroom` requires all columns in all files before checking `col_select`

### ISSUE THREAD

**Issue by jrf1111** [r-lib/vroom#305]
When getting data from my data sources, I often have to do it in chunks (old GUI software; we're working on it).  This often means I have to click through and select the variables I need multiple times. Sometimes I include an extra variable on one chunk/file but not another.  

When I import multiple files with `vroom`, it seems like I should be able to use `col_select` to select the columns I want. Even if some files have variables the others don't, as long as each file has all of the variables listed in `col_select` it seems like this should still work. 

Instead, this happens:

```
library(tidyverse)
library(vroom)

df1 = mtcars %>% select(mpg, cyl, disp, hp) %>% head()
df2 = mtcars %>% tail()

dir.create("test/")

vroom_write(df1, "test/df1.csv", delim = ",")
vroom_write(df2, "test/df2.csv", delim = ",")


files = list.files("test/", full.names = T)
combo = vroom(files, col_select = c("mpg", "cyl", "disp", "hp"))
```

With the error:
```
Error in vroom_(file, delim = delim %||% col_types$delim, col_names = col_names,  :                                                                                      
  Files must all have 4 columns:
* File 2 has 11 columns
```

Can `vroom` check to make sure all variables specified in `col_select` are present in each file instead of requiring all files to have the same number of variables? That way, the above example would return a data.frame with only `mpg`, `cyl`, `disp`, and `hp` in it?

**Comment by jimhester** [comment]
The column selection happens after indexing so what you propose is not really possible.

The files really all need to have the same structure.
