### ISSUE TITLE
vroom not enjoying reading one row (n_max=1) from some files

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/vroom#306]
file1 = 'http://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000001/ScoringFiles/PGS000001.txt.gz'
    file2 = 'http://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000117/ScoringFiles/PGS000117.txt.gz'
    vroom::vroom(file1, comment = '#', col_types = vroom::cols(.default = "c"), col_names = FALSE, n_max = 1L)
    #> # A tibble: 1 x 7
    #>   X1    X2       X3            X4               X5            X6         X7   
    #>   <chr> <chr>    <chr>         <chr>            <chr>         <chr>      <chr>
    #> 1 rsID  chr_name effect_allele reference_allele effect_weight locus_name OR

    vroom::vroom(file2, comment = '#', col_types = vroom::cols(.default = "c"), col_names = FALSE, n_max = 1L)
    #> Warning: One or more parsing issues, see `problems()` for details
    #> # A tibble: 294,369 x 6
    #>    X1           X2       X3           X4            X5              X6          
    #>    <chr>        <chr>    <chr>        <chr>         <chr>           <chr>       
    #>  1 rsID         chr_name chr_position effect_allele reference_alle… effect_weig…
    #>  2 -0.000620785 <NA>     <NA>         <NA>          <NA>            rs12143663  
    #>  3 1            26645985 G            A             -0.00053504     rs6696625   
    #>  4 1            26646128 G            A             -0.000725769    rs142035096 
    #>  5 1            26665873 C            G             0.001863845     rs10902741  
    #>  6 1            26666809 A            G             0.000696602     rs55675162  
    #>  7 1            26683548 G            A             -9.12e-05       rs58034207  
    #>  8 1            26683575 C            T             -0.000148902    rs11583205  
    #>  9 1            26684141 C            A             -6.79e-05       rs12127416  
    #> 10 1            26684403 G            A             -0.000127728    rs4659437   
    #> # … with 294,359 more rows
    vroom::vroom(file2, comment = '#', col_types = vroom::cols(.default = "c"), col_names = FALSE, n_max = 2L)
    #> # A tibble: 2 x 6
    #>   X1         X2       X3           X4            X5               X6           
    #>   <chr>      <chr>    <chr>        <chr>         <chr>            <chr>        
    #> 1 rsID       chr_name chr_position effect_allele reference_allele effect_weight
    #> 2 rs11240779 1        808631       A             G                0.00077622
    vroom::vroom(file2, comment = '#', col_types = vroom::cols(.default = "c"), col_names = FALSE, n_max = 5L)
    #> # A tibble: 5 x 6
    #>   X1         X2       X3           X4            X5               X6           
    #>   <chr>      <chr>    <chr>        <chr>         <chr>            <chr>        
    #> 1 rsID       chr_name chr_position effect_allele reference_allele effect_weight
    #> 2 rs11240779 1        808631       A             G                0.00077622   
    #> 3 rs1921     1        949608       A             G                -0.00583829  
    #> 4 rs2710890  1        958905       G             A                -0.00182583  
    #> 5 rs4970349  1        967658       T             C                -0.001855691
    vroom::vroom(file2, comment = '#', col_types = vroom::cols(.default = "c"), col_names = FALSE, n_max = 10L)
    #> # A tibble: 10 x 6
    #>    X1         X2       X3           X4            X5               X6           
    #>    <chr>      <chr>    <chr>        <chr>         <chr>            <chr>        
    #>  1 rsID       chr_name chr_position effect_allele reference_allele effect_weight
    #>  2 rs11240779 1        808631       A             G                0.00077622   
    #>  3 rs1921     1        949608       A             G                -0.00583829  
    #>  4 rs2710890  1        958905       G             A                -0.00182583  
    #>  5 rs4970349  1        967658       T             C                -0.001855691 
    #>  6 rs2710887  1        986443       T             C                -0.003430246 
    #>  7 rs3813193  1        998501       G             C                -0.000668196 
    #>  8 rs11260596 1        1002434      T             C                0.003448494  
    #>  9 rs3934834  1        1005806      C             T                -0.000977637 
    #> 10 rs9442394  1        1006223      A             G                -0.000472732

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ramiromagno** [comment]
Actually, the data frame with the problems is empty even though vroom raises the warning:

```
Warning: One or more parsing issues, see `problems()` for details
```

    library(vroom)

    read_file_column_names <- function(file) {
      
      tbl <- vroom::vroom(file,
                          comment = '#',
                          col_types = vroom::cols(.default = "c"),
                          col_names = FALSE,
                          n_max = 1L)
      unlist(tbl[1, ], use.names = FALSE)
    }

    read_pgs_scoring_file_data <- function(file) {
      
      col_types <- list(
        variant_id = vroom::col_character(),
        rsID = vroom::col_character(),
        chr_name = vroom::col_character(),
        chr_position = vroom::col_integer(),
        effect_allele = vroom::col_character(),
        reference_allele = vroom::col_character(),
        effect_weight = vroom::col_double(),
        locus_name = vroom::col_character(),
        weight_type = vroom::col_character(),
        allelefrequency_effect = vroom::col_double(),
        is_interaction = vroom::col_logical(),
        is_recessive = vroom::col_logical(),
        is_haplotype = vroom::col_logical(),
        is_diplotype = vroom::col_logical(),
        imputation_method = vroom::col_character(),
        variant_description = vroom::col_character(),
        inclusion_criteria = vroom::col_character(),
        OR = vroom::col_double(),
        HR = vroom::col_double()
      )
      
      col_names <- read_file_column_names(file)
      col_types2 <- vroom::cols(!!!col_types[col_names])
      
      tbl <- vroom::vroom(file, comment = '#', col_types = col_types2)
      
      return(tbl)
    }

    file = 'http://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000117/ScoringFiles/PGS000117.txt.gz'

    foo <- read_pgs_scoring_file_data(file)
    #> Warning: One or more parsing issues, see `problems()` for details

    problems(foo)
    #> # A tibble: 0 x 5
    #> # … with 5 variables: row <int>, col <int>, expected <chr>, actual <chr>,
    #> #   file <chr>

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jimhester** [comment]
I can reproduce this, will try to figure out what is going wrong.

A workaround is to extract the file explicitly before reading.
