### ISSUE TITLE
`problems()` not interchangable between readr and vroom

### ISSUE THREAD

**Issue by kiernann** [r-lib/vroom#308]
Not sure if this a bug _per se_ but it can be confusing when `vroom::problems()` masks `readr::problems()` and the two aren't interchangeable like `cols()`, etc.

``` r
library(tidyverse)
library(vroom) # masks readr

x <- "a,1\nb,2\nc"
dat1 <- vroom(x, delim = ",")
#> Rows: 2
#> Columns: 2
#> Delimiter: ","
#> chr [1]: a
#> dbl [1]: 1
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
problems(dat1)
#> # A tibble: 1 x 5
#>     row   col expected  actual    file                            
#>   <int> <int> <chr>     <chr>     <chr>                           
#> 1     2     1 2 columns 1 columns /tmp/RtmpQ2jTrg/file7a7066e62b63
dat2 <- read_csv(x)
#> Warning: 1 parsing failure.
#> row col  expected    actual         file
#>   2  -- 2 columns 1 columns literal data
problems(dat2)
#> Error: Invalid input type, expected 'externalptr' actual 'list'
```

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I've been loading both readr and vroom in my scripts for a while and it took me a second to find the cause of this issue after upgrading vroom.

Maybe a more detailed error asking if the user used readr?

**Comment by MatthieuStigler** [comment]
It seems that there is still a problem (using the dev version 1.4.0.9000): if `readr` is loaded, and `vroom` is not (using simply `vroom::vroom`), there is still a confusion with `readr::problems`, as `problems` links to an obscure pointer *<pointer: 0x55a4fff91140>*? 

See:

``` r
library(readr)

packageVersion("vroom")
#> [1] '1.4.0.9000'

x <- "a,1\nb,2\nc"
dat1 <- vroom::vroom(x, delim = ",")
#> Rows: 2 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (1): a
#> dbl (1): 1
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
problems(dat1)
#> <pointer: 0x55646a157fe0>
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
