### ISSUE TITLE
Specifying column types for optional columns

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vroom#317]
I have some CSV files where some of the column are optional but I still want to specify the column type. I didn't find any good way of doing this with `vroom`.

For example the column `z` is optional

``` r
library(vroom)

vroom(
  I("x,y\n1,2\n3,4\n"),
  col_types = cols(
    x = col_double(),
    y = col_double(),
    z = col_double()
  )
)
#> Warning: The following named parsers don't match the column names: z
#> # A tibble: 2 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3     4
```

<sup>Created on 2021-03-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

It basically works but I get a warning. Suppressing the warning doesn't seem like a good option to me as there might be other valid warnings. I cannot really use the `.default` argument as I have optional columns of different types.

I think `col_select` would be the easiest and most logical way how to specify these optional columns but it doesn't work as it is only applied after reading the data.

**Comment by jimhester** [comment]
Doing what you did and suppressing the warning is the best thing you can do. You can suppress just that warning with the following.

``` r
library(vroom)
suppress_warning_named_parser <- function (expr, classes = "warning") {
  withCallingHandlers(expr,
    warning = function(w) if (grepl("named parsers don't match the column name", conditionMessage(w))) {
      tryInvokeRestart("muffleWarning")
    })
}

suppress_warning_named_parser({
  vroom(
    I("x,y\n1,2\n3,4\n"),
    col_types = cols(
      x = col_double(),
      y = col_double(),
      z = col_double()
    )
  )
})
#> # A tibble: 2 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3     4
```

<sup>Created on 2021-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mgirlich** [comment]
Do you think one of the following would be a possibility?

## Argument `missing`
Add an argument `missing = c("warning", "error", "ignore")` to the `col_*()` functions. This would give the user much better control how to handle missing columns:

  * `warning`: the current behaviour
  * `error`: throw error instead of a warning
  * `ignore`: don't throw an error or a warning but create an empty column
 
I am not really a big fan of the current behaviour of producing a warning. Usually a missing column is an error for me but sometimes it might be okay. I think the current behaviour of a warning is mostly useful for interactive analysis.

## Richer warning object
The warning object could get a custom class and have the missing columns as an extra field. This would at least be more robust and simper to parse.

**Comment by jimhester** [comment]
We added a class to the warning, so with recent versions of R you can suppress just this warning with `suppressWarnings(classes =)`

---
author: jhester
date: 2021-04-29
output: "reprex::reprex\\_document"
title: cummy-krill\_reprex.R
---

``` r
library(vroom)
suppressWarnings(classes = "vroom_mismatched_column_name",
  vroom(
    I("x,y\n1,2\n3,4,,\n"),
    col_types = list(
      x = col_double(),
      y = col_double(),
      z = col_double()
    )
  )
)
#> Warning: One or more parsing issues, see `problems()` for details
#> # A tibble: 2 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3    NA
```

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
