### ISSUE TITLE
Compressed file fails (uncompressed okay)

### ISSUE THREAD

**Issue by boopsboops** [r-lib/vroom#320]
Greetings. I've been having some trouble reading in a gz compressed table. Vroom messes up some of the lines, but works if I decompress it first. `read_csv()` works fine on the compressed table. 

I hope this is enough info to find the problem. The file is not huge (116 MB, 52,767 rows, 41 cols). 

Importantly, this issue is with vroom 1.4.0. I just tested in vroom 1.3.2, and that works without any problems.

Thanks!

Some code:

```r
# remote path
file.remote <- "https://github.com/genner-lab/meta-fish-lib/raw/main/assets/reference-library-master.csv.gz"

# try with read_csv - works
readr::read_csv(file.remote,guess_max=99999) %>% spec()

# try with vroom - col types are not as expected
vroom::vroom(file.remote,delim=",",guess_max=99999) %>% spec()
vroom::vroom(file.remote,delim=",",guess_max=99999) %>% problems()
```

If I download the file locally I get the same issue with the gz archive, but if I decompress it outside of R, vroom loads it correctly.

```sh
wget "https://github.com/genner-lab/meta-fish-lib/raw/main/assets/reference-library-master.csv.gz"
gzip -dk "~/reference-library-master.csv.gz"
```
```r
# local paths
file.local.gz <- "~/reference-library-master.csv.gz"
file.local.csv <- "~/reference-library-master.csv"

# vroom incorrectly loads the gz as before
vroom::vroom(file.local.gz,delim=",",guess_max=99999) %>% problems()

# vroom loads csv correctly now
vroom::vroom(file.local.csv,delim=",",guess_max=99999) %>% problems()
```

I tracked down the issue to a specific line (20964), but I can't see what is wrong with it.

```r
# works! 
vroom::vroom(file.local.gz,delim=",",guess_max=99999,n_max=20963) %>% problems() 

# does not work :(
vroom::vroom(file.local.gz,delim=",",guess_max=99999,n_max=20964) %>% problems() 
```

**Comment by jimhester** [comment]
Can you give details on what machine you are using?

Also could you try this with the latest version of vroom? It is possible this is already fixed by https://github.com/r-lib/vroom/issues/301.

**Comment by boopsboops** [comment]
Ooops, sorry, I forgot to include that!

`as.list(Sys.info())`

$sysname
[1] "Linux"

$release
[1] "4.15.0-140-generic"

$version
[1] "#144~16.04.1-Ubuntu SMP Fri Mar 19 21:24:12 UTC 2021"

$machine
[1] "x86_64"


`as.list(R.Version())`

$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.4"

$year
[1] "2021"

$month
[1] "02"

$day
[1] "15"

$svn rev
[1] "80002"

$language
[1] "R"

$version.string
[1] "R version 4.0.4 (2021-02-15)"

$nickname
[1] "Lost Library Book"

**Comment by boopsboops** [comment]
And also, yes, just installed the latest dev vroom and that has fixed it. Cheers!

```
renv::install("r-lib/vroom@4ec3f8866de7061229a4f2e95f84cf4dad120e0d")
library("vroom")
packageVersion("vroom")
[1] ‘1.4.0.9000’
```
