### ISSUE TITLE
Re-license vroom to MIT

### ISSUE THREAD

**Issue by hadley** [r-lib/vroom#323]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/vroom/graphs/contributors). @CriscelyLP, @edzer, @meta00, @R3myG, @wlattner, would you permit us to re-license vroom with the MIT license? If so, please comment "I agree" below.

* [x] [@CriscelyLP](https://github.com/r-lib/vroom/commits?author=CriscelyLP)  
* [x] [@edzer](https://github.com/r-lib/vroom/commits?author=edzer)  
* [x] [@meta00](https://github.com/r-lib/vroom/commits?author=meta00)  
* [x] [@R3myG](https://github.com/r-lib/vroom/commits?author=R3myG)  
* [x] [@wlattner](https://github.com/r-lib/vroom/commits?author=wlattner)

**Comment by R3myG** [comment]
I agree

**Comment by CriscelyLP** [comment]
I agree !

**Comment by edzer** [comment]
I agree!

**Comment by wlattner** [comment]
I agree

**Comment by meta00** [comment]
I agree
