### ISSUE TITLE
na values not respected in numeric columns.

### ISSUE THREAD

**Issue by BEFH** [r-lib/vroom#342]
In vroom 1.4.0, the `na` argument to the `vroom()` is not respected for numeric columns if the NA string is numeric. Numeric NA strings are respected in string columns, and non-numeric NA strings are also respected in numeric columns.

For example, if the input file (test2.csv) is as follows:

```
strcol,numcol
foo,1
bar,-9
spam,3
-9,spam
```

and I run `vroom::vroom("test2.csv", na = c("-9", "spam"))`, the output is as follows:

```
# A tibble: 4 x 2
  strcol numcol
  <chr>   <dbl>
1 foo         1
2 bar        -9
3 NA          3
4 NA         NA
```

However, if I use `read_tsv()` from `readr`, the file is properly parsed. The result of `readr::read_csv("test2.csv", na = c("-9", "spam"))` is correct:

```
# A tibble: 4 x 2
  strcol numcol
  <chr>   <dbl>
1 foo         1
2 bar        NA
3 NA          3
4 NA         NA
```

Datasets often use numbers such as -9 or 999 to represent NA in numeric fields, so this is a fairly serious bug, and the inconsistent behavior is also surprising.

**Comment by jimhester** [comment]
Thank you for opening the issue and for supplying a reproducible example, it is a big help!

It should be fixed now.

**Comment by BEFH** [comment]
Will this be in vroom 1.5.0? Thanks for maintaining vroom; I’m switching to it for all of my new scripts!

**Comment by jimhester** [comment]
no, vroom 1.5.0 is already submitted.
