### ISSUE TITLE
Segmentation fault with `use_threads`  on some systems

### ISSUE THREAD

**Issue by hsbadr** [r-lib/vroom#347]
@jimhester I hit a segmentation fault (similar to [this ERROR](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/vroom-00check.html) on CRAN) with `use_threads`  and `libstdc++` on some systems (822e9270f6660ee2c84713d39060200924848f3f doesn't fix it for all cases). Let me know if you want me to test a patch.

```r
> vroom::vroom(file = vroom::vroom_example("mtcars.csv"), delim = ",")

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: vroom_(file, delim = delim %||% col_types$delim, col_names = col_names,     col_types = col_types, id = id, skip = skip, col_select = col_select,     name_repair = .name_repair, na = na, quote = quote, trim_ws = trim_ws,     escape_double = escape_double, escape_backslash = escape_backslash,     comment = comment, skip_empty_rows = skip_empty_rows, locale = locale,     guess_max = guess_max, n_max = n_max, altrep = vroom_altrep(altrep),     num_threads = num_threads, progress = progress)
 2: vroom::vroom(file = vroom::vroom_example("mtcars.csv"), delim = ",")
```

Disabling threads temporarily fixes the problem for me:
```diff
diff --git a/src/parallel.h b/src/parallel.h
index 08c8d2b..68d0fb9 100644
--- a/src/parallel.h
+++ b/src/parallel.h
@@ -27,10 +27,8 @@ static std::vector<std::future<void>> parallel_for(
     bool use_threads = true,
     bool cleanup = true) {

-#if !defined __APPLE__ && defined _LIBCPP_VERSION
   use_threads = false;
   nb_threads = 1;
-#endif

   size_t batch_size = nb_elements / nb_threads;
```

```r
> sessionInfo()
R Under development (unstable) (2021-06-24 r80552)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /opt/intel/oneapi/mkl/2021.2.0/lib/intel64/libmkl_intel_lp64.so.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.0
```

**Comment by jimhester** [comment]
What is the system? The example you gave is run many times in the tests and doesn't exhibit this behavior, I need to be able to reproduce this to fix it.

**Comment by hsbadr** [comment]
> What is the system? The example you gave is run many times in the tests and doesn't exhibit this behavior, I need to be able to reproduce this to fix it.

This happens on Ubuntu 20.04 and18.04 LTS with R-devel compiled from source code using Intel compilers and MKL. `vroom` and all of its dependencies are freshly installed from GitHub. The sane configurations on Ubuntu 16.04 LTS but everything installed from CRAN, the problem doesn't exist. I've reinstalled and tested all libraries and only `vroom` fails when `use_threads` is enabled. I guess it's a combination of the version of `libstdc++`/`libc++` and `vroom` dependencies.

I currently use `readr` with the 1st edition to avoid this issue, but I saw the error on CRAN and 822e9270f6660ee2c84713d39060200924848f3f so I wanted to let you know that there's other cases (besides `defined _LIBCPP_VERSION`). You can ignore my issue if you can't reproduce it, but I could help if you'd like to test patches to the use of  `std::future`, for example. Anyway, I'll report it here if any future changes will fix this.

**Comment by jimhester** [comment]
So you are compiling vroom R with icc, intel's compiler? I can try this and see what happens.

**Comment by hsbadr** [comment]
> So you are compiling vroom R with icc, intel's compiler? I can try this and see what happens.

Yes, and that causes no problem when the other dependencies are installed from CRAN. I've also tested `vroom v1.4`, which doesn't work with the development version of `cpp11`:
```r
vroom.so: undefined symbol: _ZN5cpp112naIdEET_v
```
But, it works with the CRAN version.

I think you need to install the development version of all dependencies to reproduce this (if it's due to a dependency not a system library). This may not be worth it unless you want to find and fix the root cause of the incompatibility issue. It seems to be due to one of the dependencies though since Intel compilers cause no problem on another server.

In general, I think `std::future` is not thread-safe, and I'm not sure if using `std::shared_future` would fix it.

**Comment by hsbadr** [comment]
@jimhester I've been able to reproduce this issue by installing and defaulting to GCC 11.1 before compiling `vroom`.
```bash
> gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Reverting to GCC 10.3 and recompiling `vroom` fixes the issue.

**Comment by hsbadr** [comment]
After debugging, this is an Intel `icpc` compiler issue with `gcc v11.1.0` and `std::future`. Simple examples fail in this environment and work fine when compiling with `g++`. For `vroom`, you may ignore this or disable threading if Intel compilers are used with `gcc version > 11.0`. I'm closing this issue.

**Comment by jimhester** [comment]
Why aren't you compiling vroom with icpc if R is compiled with icpc?

**Comment by jimhester** [comment]
In any case, it seems like you were possibly mixing C++ standard library versions, using headers for one and linking to a different version. You will want to make sure you are compiling and linking the package with the same standard library headers, see https://stackoverflow.com/questions/37122526/using-different-standard-c-library-headers-with-intel-compiler which has some examples on how to set these explicitly if needed.

**Comment by hsbadr** [comment]
> Why aren't you compiling vroom with icpc if R is compiled with icpc?

I do. That's the source of the problem. `icpc` uses the C++ standard library from the default GCC. That works with all versions < 11.0. We can specify a version using `-gxx-name=<>` (g++ binary path or name; e.g., `g++-10`) or  `-cxxlib=<>`.

This issue happens when `vroom` (or any code that uses `std::future`) is compiled with Intel compilers while g++ v11+ is the default in the PATH. Specifying an older version with the compiler flags would fix it too.

**Comment by hsbadr** [comment]
> In any case, it seems like you were possibly mixing C++ standard library versions, using headers for one and linking to a different version. You will want to make sure you are compiling and linking the package with the same standard library headers, see https://stackoverflow.com/questions/37122526/using-different-standard-c-library-headers-with-intel-compiler which has some examples on how to set these explicitly if needed.

The Intel C++ compiler is compatible with most versions of GCC. It seems that GCC v11 isn't supported yet.
