### ISSUE TITLE
Automatically detect file compression for local files

### ISSUE THREAD

**Issue by jimhester** [r-lib/vroom#348]
readr does this, and at least 1 package (PL94171) depends on this.

https://github.com/tidyverse/readr/blob/aa8a502c62095c4aebba721b23b9a954ebab4e82/R/source.R#L244-L294

**Comment by cboettig** [comment]
@jimhester assuming this requires we download the file first though, or will this work with remote sources too? (iirc we could stream `.csv.gz` but not other compression formats from URLs before)

**Comment by jimhester** [comment]
This detection is only done for local files.
