### ISSUE TITLE
Possible truncation at >4GB [potential solution?]

### ISSUE THREAD

**Issue by lime-n** [r-lib/vroom#350]
I keep getting the issue when unzipping a 174gb .zip file:

possible truncation of >= 4GB file

I know that it's an R problem, however, is there a way around this? otherwise, can something like looping over the .zip decompression until the until file is complete? 
or extracting every 4gb, saving it as an individual file that saves less on memory, over and over again until complete, then accessing them all with `list.files`, somehow determining which last 4gb of data was extracted sounds rather tricky.

**Comment by jimhester** [comment]
Use `vroom::vroom(archive::archive_read("my_file.zip"))`, which should support files larger than 4Gb, unlike the implementation in base R.

**Comment by lime-n** [comment]
That does work although my issue next would be the size of my file relative to hard-drive/RAM. 

Would it be possible to run this in chunks? For example, my file is 174GB and 800gb uncompressed, running perhaps the first 100gb then saving it (for filtering so I can remove it after), then decompressing the next 100gb? etc ...

**Comment by jimhester** [comment]
R is really primarily designed for in-memory data processing, so if your data is too big to fit in memory on your machine you will need to come up with an alternative solution.

One possible solution would be for you to partition it outside of R, then process each of the partition individually.

Or you could see if you can condense or summarize the data in some way before trying to ingest it in R.

In any case, the vroom issue tracker is not really the place for these discussions. If you would like to discuss possible strategies for handling this data asking on <https://community.rstudio.com> is probably the best bet.
