### ISSUE TITLE
`NA` intepreted as logical 

### ISSUE THREAD

**Issue by rmcd1024** [r-lib/vroom#352]
If a csv file consists of `NA` repeated 100 times followed by a number, for example `5`, `vroom` infers a column type of `lgl`. Shouldn't  this case should be treated as `dbl` or `int`? This creates a genuine problem when there are CSV files with millions of rows and some columns have a high percentage of NA. The `problems()` function is then very slow to create its tibble when the user investigates the `problems` warning.

To duplicate using the current development version:
``` r
``` r
library(readr)
library(vroom)
write_csv(data.frame('var' = c(rep(NA, 100), 5)), file = '/tmp/test.csv')
vroom('/tmp/test.csv', delim = ',')
#> Warning: One or more parsing issues, see `problems()` for details
#> Rows: 101 Columns: 1
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> lgl (1): var
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 101 x 1
#>    var  
#>    <lgl>
#>  1 NA   
#>  2 NA   
#>  3 NA   
#>  4 NA   
#>  5 NA   
#>  6 NA   
#>  7 NA   
#>  8 NA   
#>  9 NA   
#> 10 NA   
#> # … with 91 more rows
sessionInfo()
#> R version 4.1.0 (2021-05-18)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.2 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] vroom_1.5.1.9000 readr_1.4.0     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.33        magrittr_2.0.1    hms_1.1.0        
#>  [5] tidyselect_1.1.1  bit_4.0.4         R6_2.5.0          rlang_0.4.11     
#>  [9] fansi_0.5.0       stringr_1.4.0     styler_1.4.1      highr_0.9        
#> [13] tools_4.1.0       parallel_4.1.0    xfun_0.24         utf8_1.2.1       
#> [17] cli_3.0.0         withr_2.4.2       htmltools_0.5.1.1 ellipsis_0.3.2   
#> [21] bit64_4.0.5       yaml_2.2.1        digest_0.6.27     tibble_3.1.2     
#> [25] lifecycle_1.0.0   crayon_1.4.1      tzdb_0.1.1        purrr_0.3.4      
#> [29] vctrs_0.3.8       fs_1.5.0          glue_1.4.2        evaluate_0.14    
#> [33] rmarkdown_2.9.1   reprex_2.0.0      stringi_1.6.2     compiler_4.1.0   
#> [37] pillar_1.6.1      backports_1.2.1   pkgconfig_2.0.3
```

<sup>Created on 2021-07-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment]
This is the same behavior as readr, readr just uses a different default value for `guess_max`.

``` r
write.csv(data.frame('var' = c(rep(NA, 100), 5)), file = '/tmp/test.csv', row.names = FALSE)
readr::read_csv("/tmp/test.csv", guess_max = 100)
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   var = col_logical()
#> )
#> Warning: 1 parsing failure.
#> row col           expected actual            file
#> 101 var 1/0/T/F/TRUE/FALSE      5 '/tmp/test.csv'
#> # A tibble: 101 x 1
#>    var  
#>    <lgl>
#>  1 NA   
#>  2 NA   
#>  3 NA   
#>  4 NA   
#>  5 NA   
#>  6 NA   
#>  7 NA   
#>  8 NA   
#>  9 NA   
#> 10 NA   
#> # … with 91 more rows
```

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

In fact vroom generally does this guessing better than readr currently does. Readr always uses the first `guess_max` number of rows for guessing, whereas vroom uses rows interspersed throughout the file if `guess_max` is less than the total number of rows.

However as this example shows we should probably always include the last row when guessing, so I have made a change to always include the last row in the guess in the future.

As noted in `?problems` by default calling `problems()` will read the entire dataset first to report all problems. If you only want to see the problems that have been found so far you can use `problems(lazy = TRUE)`.

But in general relying on guessing for datasets with a high number of missing values will always be problematic. No guess can ever be fully accurate unless it uses all of the data (e.g. `guess_max = Inf`).

**Comment by rmcd1024** [comment]
Thanks for the response. Checking the last value will handle my case :-)

However, given that `vroom` is doing a lot of indexing, I've been wondering why `vroom` doesn't adopt the `data.table::fread` strategy of sampling the data at intervals to determine data types. My experience has been that `fread` is not only faster than `read_csv` (version 1.4 and lower) but also does a much better job of inferring data types.

**Comment by jimhester** [comment]
It does sample, it just happens that it wasn't sampling the last row in this case.

> whereas vroom uses rows interspersed throughout the file
