### ISSUE TITLE
trim_ws, trim whitespaces doesn't work

### ISSUE THREAD

**Issue by AlexMehn** [r-lib/vroom#354]
Hello,
i'm using R version 4.0.2 and vroom Version 1.5.2 on a Windows 10 System.

The Problem is as follows; i'm importing a txt data file with vroom and some cells have only whitespaces in them. Or some Names have leading or trailing whitespaces. I'm using trim_ws = TRUE but the whitespaces ar still there. And the semingly emtpy cell is not NA. In my opinion it should be NA, because it only contains whitespaces, so i understand the function of trim_ws.

Used Code:
library(vroom)
test_vroom <- vroom("Testdatensatz.dat", delim = "@", trim_ws = TRUE, na = c("", " ", "NA"))

[Testdatensatz.txt](https://github.com/r-lib/vroom/files/6807300/Testdatensatz.txt)

**Comment by jimhester** [comment]
Thanks for opening the issue!

Keeping whitespace within quotes was actually explicitly tested for regardless of the setting of `trim_ws`. The rational was that if the input data used quotes the whitespace was probably there purposefully.

However revisiting this it seems like somewhat surprising behavior, and also departs from what is done currently in readr.

Therefore we now trim the whitespace in quoted fields as well if `trim_ws = TRUE`.
