### ISSUE TITLE
vroom unhelpful for large data files on /tmp with tmpfs file system

### ISSUE THREAD

**Issue by eshom** [r-lib/vroom#368]
One of the great things about `vroom` is being able to read data out-of-memory and operate on it using native R code. However, this fails when /tmp is mounted as tmpfs, because `vroom` stores temporary files, taking up RAM in these cases, completely negating the out-of-memory advantage.

 I know tmpfs for /tmp is at least the default for Linux distributions such as openSUSE (which I use). So it would be helpful to have an option to choose where temporary files would be stored. Is there such an option?

Edit: I think this is really only an issue with compressed files. Otherwise `vroom` doesn't generate temporary files:
``` r
mygz <- tempfile()
myfile <- tempfile()

write.csv(mtcars, gzfile(mygz))
write.csv(mtcars, myfile)

mydata_gz <- vroom::vroom(mygz)
#> New names:
#> * `` -> ...1
#> Rows: 32 Columns: 12
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (1): ...1
#> dbl (11): mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
mydata <- vroom::vroom(myfile)
#> New names:
#> * `` -> ...1
#> Rows: 32 Columns: 12
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (1): ...1
#> dbl (11): mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

list.files(tempdir())
#> [1] "file1522fa97a9d"   "file15249146cc4"   "vroom-15255123010"
```

Thanks.

**Comment by jimhester** [comment]
You can control where the temporary files are stored, `VROOM_TEMP_PATH` (https://github.com/r-lib/vroom#environment-variables)

**Comment by eshom** [comment]
Ah, thanks! I'm happy to see this is already implemented.
