### ISSUE TITLE
Specifying folder to read from when reading multiple files - enhancement

### ISSUE THREAD

**Issue by ScoobyQ** [r-lib/vroom#369]
Does reading multiple files allow for specifying the directory to read from? Looking at the [given example ](https://www.tidyverse.org/blog/2019/05/vroom-1-0-0/#reading-multiple-files)of `fs::dir_ls(glob = "flights_*tsv")` - I can't see where one specifies directory so assume one set the working directory first. Is it possible to add this enhancement if not present?

**Comment by jimhester** [comment]
vroom just takes an absolute or relative path to the files, e.g.

```r
vroom::vroom(c("foo/data.csv", "bar/data.csv"))
```

If this question is about how to specify the root directory in `dir_ls()` you use the `path` argument.
