### ISSUE TITLE
vroom command locks a target file in a Windows system. So the target file cannot edit after reading while R session is still running.

### ISSUE THREAD

**Issue by t32ak1** [r-lib/vroom#371]
When I read a CSV file with readr::read_csv in R running in a windows system, the CSV file cannot edit after reading if R session keeps running.
Now, readr::read_* functions are wrappers for vroom::vroom, therefore I write a Issue for vroom. 

Example: 
1) a CSV file are saved in a some folder (ex. C:\temp).
[test_csv.csv](https://github.com/r-lib/vroom/files/7141559/test_csv.csv)

2) R sessions are started and read the CSV file with vroom::vroom
```
PS C:\temp> R.exe
vroom::vroom('test_csv.csv')
```

3) Trying to change the content of a target CSV file with an editor (like VS code) or some office suites (like LibreOffice), but the editor / office suites say "I/O Error" when that target CSV file is trying to save.
```
VSCode:  (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'c:\temp\test_csv.csv')
```

Is the setting wrong in my windows system?
Is there a way around it?

Please give some advices.

System:
 Windows: Windows 10 Pro 64bit 21H1 (Build 19043.1202)
 R: version.string R version 4.1.1 (2021-08-10)
 vroom:
 packageVersion("vroom")
 [1] '1.5.4.9000'

**Comment by jimhester** [comment]
The file is locked because it is read lazily, e.g. the data is not fully parsed until it is needed. Once all the data has been read the file handle will be automatically removed.

If you use `altrep = FALSE` to instead read the file eagerly you will be able to edit the file as expected.

**Comment by jimhester** [comment]
If you are using vroom through readr function the argument is `lazy = FALSE`.

**Comment by t32ak1** [comment]
Following your advice, I was able to edit the file as expected.

I'm sorry I missed the latest document.
It was my lack of attention.

Thank you for your generous and proper advice.
