### ISSUE TITLE
fwf_empty() can't handle a URL

### ISSUE THREAD

**Issue by NikKrieger** [r-lib/vroom#374]
Isn't this supposed to be able to handle a URL?

``` r
vroom::fwf_empty("https://www2.census.gov/geo/docs/reference/cenpop2000/statecenters.txt")
#> Error: `file` must be a regular file, not a connection
```

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment]
No, because if it did then you would have to read the URL twice, e.g. once for `fwf_empty()` to figure out the column widths and once for `vroom_fwf()`.

If you want to do this the best way is to download the file and then read it, e.g.

```r
my_read_fwf <- function(url) {
  f <- tempfile()
  download.file(url, f)
  on.exit(unlink(f))
  vroom::vroom_fwf(f, col_positions = fwf_empty(url))
}
```

**Comment by NikKrieger** [comment]
That makes sense based on the default argument expression in `vroom::read_fwf()`. I believe this should be mentioned in `@param file`, though, because in my opinion it currently implies that it can indeed handle URLs:

> Files starting with `http://`, `https://`, `ftp://`, or `ftps://` will be automatically downloaded.

I do realize that that line probably has the `file` argument of `vroom::fwf()` in mind, rather than the `file` argument of `vroom::fwf_empty()`.
