### ISSUE TITLE
Inconsistency in accepted formats for file argument

### ISSUE THREAD

**Issue by NFA** [r-lib/vroom#376]
Hello,

I was in the progress of updating one of my packages (laboratory results PDF into tibble) that depend on `readr`. During that process I updated the dependency packages and introduced some errors due to different handling in edition/version 2 of `readr`.

Specifically, I was calling `readr::fwf_empty` with a file argument that was a vector of rows from a table I wanted to parse. With the updated dependencies it tries to look for a file in the first position of the vector. So I read the documentation and found that literal data should be one string now. However, by accident I discovered that just adding a newline at the end to each vector element also solved the issue. Let me illustrate with a short example:
```
file <- vroom_example("mtcars-4.csv")
table_lines <- read_lines(file)

# 1. This will error, no file table_lines[1] in current directory
vroom(table_lines)

# 2. Same vector of rows but with \n at the end of each element works
vroom(paste(table_lines, "\n"))

# 3. A single string with line breaks between rows work
vroom(paste(table_lines, collapse = "\n"))
```

Right now I changed to do (2), since in my codebase it was a 1 line change. I have a lot of other functions that sanitizes/verifies my tables based on a vector of rows format. It is quite handy to have `vroom_result[x,]` corresponding to `table_lines[x]`.  But it also means I have a textual `\n` in the last column that I need to clean out.

Simply, I am wondering if the break to using vector of rows (1) is intended. Secondy, if it is coincidence that adding `\n` works, and that I should switch to use a single literal string instead.

Thank you for a wonderful package family.

Best regards  /NFA

**Comment by jimhester** [comment]
Yes, it is intended, see https://github.com/tidyverse/readr/blob/master/NEWS.md#literal-data.

You should use `I()` to mark the input as literal data.

**Comment by NFA** [comment]
Ok, thank you for the clarification. I will use `I()` instead for this issue. This I was thrown off using `I()` because the documentation said _"To be recognised as a path, it must be wrapped with `I()`"_, and I assumed path to mean file path.

**Comment by jimhester** [comment]
I agree the way that documentation was worded is confusing, I have updated it to hopefully be clearer.
