### ISSUE TITLE
Hang issues with some CSV file parsing on Windows (/r/n)

### ISSUE THREAD

**Issue by slodge** [r-lib/vroom#379]
I've reproduced a hang issue with `readr` 2.0.2 - see https://github.com/tidyverse/readr/issues/1310

```
csv <- "Col1,Col2\r\n"
readr::read_csv(csv) # hangs
```

This does not occur with
```
csv <- "Col1,Col2\n"
readr::read_csv(csv) # ok
```

This seems to be occurring somewhere in C++ in vroom. I've not managed to step into this to debug it, but I can see a number of fixes/changes around `\r\n` around Sep 10th - e.g. https://github.com/r-lib/vroom/commit/b3ba15212978253174c9f99f1098799cca9a6f74 - so guessing they might be related

Reproduced with:
```
>   packageVersion("readr")
[1] ‘2.0.2’
> packageVersion("vroom")
[1] ‘1.5.5’
```

Does not seem to occur in:
```
>   packageVersion("readr")
[1] ‘2.0.1’
>   packageVersion("vroom")
[1] ‘1.5.4’
```

There's a chance https://github.com/tidyverse/readr/issues/1309 might also related to the same issue?

**Comment by jimhester** [comment]
This is resolved by https://github.com/r-lib/vroom/commit/303d385401a97ef4014d575b819a67675a7cbddd
