### ISSUE TITLE
Unable to read a file when setting `vroom(col_names = FALSE, col_select = c(1, 2))` (Linux/Windows)

### ISSUE THREAD

**Issue by arisp99** [r-lib/vroom#381]
Hello!

When using Github Actions and setting `vroom(col_names = FALSE)`, I am unable to read a file on Linux and Windows, but can on macOS. Unfortunately, I am using a mac, so I have been unable to reproduce this error locally. 

I am not sure if this is the place to report this or in https://github.com/r-lib/actions, but I suspect that `{vroom}` is the culprit. I have created an example package (https://github.com/arisp99/testactionspkg) which defines the following function:

```r
read <- function(.file,
                 .col_names = FALSE,
                 .col_select = everything(),
                 .name_repair = "unique") {
  vroom::vroom(
    file = .file,
    col_names = .col_names,
    col_select = .col_select,
    show_col_types = FALSE,
    .name_repair = .name_repair
  )
}
```

When I attempt to use this function in a vignette: `testactionspkg::read(path, .col_names = FALSE)`, I get the following error on Github Actions for Windows and Ubuntu when running an R CMD check workflow derived from https://github.com/r-lib/actions:

```r
* creating vignettes ... ERROR
Error: --- re-building 'read-file.Rmd' using rmarkdown
Quitting from lines 24-25 (read-file.Rmd) 
Error: Error: processing vignette 'read-file.Rmd' failed with diagnostics:
Names repair functions can't return `NA` values.
--- failed re-building 'read-file.Rmd'
SUMMARY: processing the following file failed:
  'read-file.Rmd'
Error: Error: Vignette re-building failed.
Execution halted
Error: Error in proc$get_built_file() : Build process failed
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.
```

Here is a link to the GHA: https://github.com/arisp99/testactionspkg/runs/3969422512?check_suite_focus=true run.

A reprex for those working on Linux or Windows is below (this should fail, but I cannot test it...):
```r
data <- tibble::tribble(
              ~X1,                ~X2,                ~X3,
        "Gene ID",    "PF3D7_0106300",    "PF3D7_0523000",
           "Gene",             "atp6",             "mdr1",
  "Mutation Name",   "atp6-Ala623Glu",    "mdr1-Asn86Tyr",
     "ExonicFunc", "missense_variant", "missense_variant",
      "AA Change",        "Ala623Glu",         "Asn86Tyr",
       "Targeted",              "Yes",              "Yes",
     "D10-JJJ-23",                "0",               "13",
     "D10-JJJ-43",                "0",                "0"
  )

vroom::vroom_write(data, "~/Desktop/file.csv")

vroom::vroom(
    file = "~/Desktop/file.csv",
    col_names = FALSE,
    show_col_types = FALSE,
  )
```

Any insight would be appreciated! Thanks!

**Comment by jimhester** [comment]
Thank you for opening the issue and for supplying a reproducible example, it is a big help!

This should be fixed in the next release of vroom.
