### ISSUE TITLE
I have a problem when install this package. Help

### ISSUE THREAD

**Issue by LuisQ95** [r-lib/vroom#84]
Hi, I have a problem on my R when install vroom

Downloading GitHub repo r-lib/vroom@master
Error: Could not find tools necessary to compile a package

**Comment by jimhester** [comment]
vroom contains C++ code, you need to have build tools installed to compile it. See [Setting up a dev environment](https://whattheyforgot.org/set-up-an-r-dev-environment.html) for details on how to do this.
